### ISSUE TITLE
how to use mina to deploy

### ISSUE THREAD

**Issue by scriptfans** [anycable/anycable-rails#1]
How to use [mina](https://github.com/mina-deploy/mina) to deploy anycale server? thanks.

**Comment by palkan** [comment]
Do you want to deploy RPC server or websocket server (such as `anycable-go`) or both?

I guess, that only the RPC one. Then we have to add a daemonization and related stuff (like pid file, control script, etc).

For now you can do the following:

- write a pid to a file on server start:

```ruby
# ./bin/anycable
...

File.open("./tmp/pids/anycable.pid", 'w') do |f|
  f.puts ::Process.pid
end
# ensure that pid is deleted on script exit,
# we can use the existence of the file in order to check, that server is running
at_exit { File.unlink("./tmp/pids/anycable.pid") }
```

- `anycable:start` task:

```sh
# simply run anycable in background
./bin/anycable &
```

- `anycable:stop` task:

```sh
# send SIGINT to stop the server
kill -2 `cat tmp/pids/anycable.pid` 
```

**Comment by scriptfans** [comment]
I got it, thanks! but what about anycable-go server? Is there a stop/reboot command?

**Comment by palkan** [comment]
No, nothing like that. It would be great to wrap it into a system service ('cause it's more like that than an application).

Btw, you don't have to restart anycable-go on the application deployment, it's a long-running process.

**Comment by palkan** [comment]
Closing the issue.
@scriptfans  Please, comment here if you have any questions left according to Mina setup.

**Comment by alekseyl** [comment]
> ./bin/anycable &

а из тасков это как предлагается вызывать?  если через sh, exec и пр., то потом kill -2 `cat tmp/pids/anycable.pid` не пройдет. SIGINT не пройдет из-за особенности бэкграунд процессов при запуске в /bin/sh.

Можно отправить другой сигнал или в bin/sh вызвать bash с параметром, но тогда надо будет делать disown или процесс помрет вместе с bash'ем.

**Comment by palkan** [comment]
SIGKILL (`kill -9`), кажется, везде проходит. Можно использовать его, нет никакой разницы, пока нет поддержки сигналов.

В идеале нужен встроенный `daemonize` режим (как, например, в [`sidekiq`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L183)). А это уже полноценный CLI.
