### ISSUE TITLE
Questions on how to use

### ISSUE THREAD

**Issue by EsdrasEtrenne** [anycable/anycable-rails#10]
This looks really great I just have some questions on how to use it.

I notice that in the installation the gem `anycable-rails` has `group: :production` next to it. Is this only able to be used in a production environment and not a development environtment? Or am I misinterpreting what production means there. 

Also, when we run `./bin/anycable` is that all we need to run in the terminal? When I run that command in the terminal I don't get any response. I added a print statement saying `Server is running` to the bin file and it does print so I am assuming the anycable server is running at that point? If the server is running then I can't use that same terminal window to run my actual api server though right? So do I need to run my rails api from a different terminal window? (the one that runs on localhost:3000 during development)

I can tell this gem is very useful I am not the best at rails yet so  I will have a few questions while learning to implement this. I already implemented action cable with my rails app I just want to switch over to something faster and this seems to be able to do just that. Im sure I will have questions on deployment with this too once I get there as I am deploying using Amazon Web Services. 

Thank you for building this

**Comment by palkan** [comment]
> Is this only able to be used in a production environment and not a development environtment?

You can use it in any environment, but it's assumed to be used only in production to avoid running dependencies locally (such as `anycable-go`).

You can use built-in ActionCable server in development, 'cause AnyCable is [compatible](https://github.com/anycable/anycable-rails#actioncable-compatibility) with it.

If you want to run AnyCable in development then you have to run 3 processes at once: Rails server, AnyCable server and WebSocket sever (see [example Procfile](https://github.com/anycable/anycable_demo/blob/master/Procfile.dev)).

> So do I need to run my rails api from a different terminal window?

Yes, you need to. Anycable server is only responsible for communicating with WebSocket server.

**Comment by EsdrasEtrenne** [comment]
OK thank you a lot. So do I just build out everything using Action Cable as I would normally and then just switch out the ws address when ready to launch?

It looks like a very simple process from the documentation I just want to make sure I am approaching development the right way so that I don't need to change large amounts of code later

Thank you

**Comment by palkan** [comment]
Yep, that's the way it should be – just switch to AnyCable in production.

Check out the Compatibility table and [known issues](https://github.com/anycable/anycable/issues) for not supported (yet) features.

**Comment by EsdrasEtrenne** [comment]
Ok great, thank you. I will just build for now and look more deeply into integration when I am ready for production. Thank you for answering my questions! I feel like I will have more later when I start to integrate it

**Comment by xlts** [comment]
@palkan one more question about usage/debugging: is it possible to get the rpc process (`./bin/anycable`) to display access logs similar to those produced by pure ActionCable? I see it's possible to enable logging for WS server (e.g. `anycable-go`), but can I have it on rails side? I already have log rotation set up in my rails app, and it works well with pure ActionCable, however it seems that if I switch to Anycable I would lose the ability to easily collect WS access logs.

**Comment by palkan** [comment]
Hi, @xlts!

What kind of logs do you want to collect? I guess, you mean "Started ..." and "Finished ..." messages. 

Currently, AnyCable RPC knows as little as necessary about the _real_ HTTP connection (that's intentional – to reduce the amount of data to be transferred between WS and RPC) – so, for example, we don't know about IP address (which is included in ActionCable logs). But we're working on making this behaviour more flexible (see https://github.com/anycable/anycable/issues/14).

Thus right now we can add only "<event> <timestamp>" logs without any specifics.

Nevertheless, I'd like to have access logs (to be compatible with ActionCable). I've added an issue https://github.com/anycable/anycable/issues/20.

**Comment by palkan** [comment]
Closing this one in favour of separate specific issues.
