### ISSUE TITLE
Handle multiple subscriptions to the same channel in a single connection

### ISSUE THREAD

**Issue by arthurmde** [anycable/anycable-rails#100]
### Tell us about your environment

**Ruby version:** 2.5.1

**Rails version:** 5.2.3

**`anycable` gem version:** 0.6.3

**`anycable-rails` gem version:** 0.6.4

**`grpc` gem version:** 1.22

### What did you do?

As a client, I subscribed multiple times to the same channel in a single connection.

### What did you expect to happen?

I expected Anycable to work like ActionCable by keeping only one subscription for the same connection so that I would receive each streamed message only once.

### What actually happened?

The duplicated subscriptions make Anycable sending the same message multiple times through the same connection. As a consequence, the client may either react to the same event multiple times or handle the duplications by itself.

### Notes
- I am sorry if this is not the proper repository for this issue. Let me know if it is not =)
- If this is the desired behavior, IMHO Anycable could at least offer a configuration option to avoid duplicated subscriptions.

**Comment by palkan** [comment]
This is not desired behavior.

Which AnyCable server do you use? `anycable-go`?

Do you subscribe to the same channel with different params?r

**Comment by arthurmde** [comment]
@palkan This is not a bug. The described behavior does not exist.

Sorry. It was my mistake =)

I'm using EmberJS frontend application as the client. The problem was that I had many components registering async handlers for received messages. This design gave me the false feeling that I was receiving multiple messages from the backend WebSocket server (Anycable).
