### ISSUE TITLE
Authenticate response: error_msg:"undefined method `protocol' for nil:NilClass"

### ISSUE THREAD

**Issue by subhashsaran** [anycable/anycable-rails#103]
### Tell us about your environment

**Ruby version:** 2.6.2

**Rails version:**5.2.2

**`anycable` gem version:** 0.6.3

**`anycable-rails` gem version:**0.6.4

**`grpc` gem version:** 1.17

### What did you do?
I did setup anycable with existing Rails app which was using action cable earlier, I managed to have it working on dev environment but when deployed to production I get authentication error, 
this issue is not related to  [troubleshooting](https://docs.anycable.io/#/troubleshooting?id=my-websocket-connection-fails-with-quotauth-failedquot-error) but seems different. 

we have deployed on heroku with two apps setup as suggested. one app is running rails application on a subdomain and another one is running anycable rpc server on another subdomain. we have supplied `domain: :all` option in `session_store.rb`.

### What did you expect to happen?
Expected Anycable to work fine.

### What actually happened?
Error backtrace from production.
```
2019-08-27T03:43:46.812300+00:00 app[web.1]: [AnyCable sid=caSj90W6eSG3l9kagpJDVD] method={} path={} format={} params={} controller=ApplicationCable::Connection action=connect status=500 error='NoMethodError: undefined method `protocol' for nil:NilClass' duration=1.33
2019-08-27T03:43:46.812368+00:00 app[web.1]: [AnyCable sid=caSj90W6eSG3l9kagpJDVD] undefined method `protocol' for nil:NilClass
2019-08-27T03:43:46.812714+00:00 app[web.1]: D 2019-08-27T03:43:46.812Z context=rpc Authenticate response: error_msg:"undefined method `protocol' for nil:NilClass"
2019-08-27T03:43:46.812907+00:00 app[web.1]: D 2019-08-27T03:43:46.812Z context=ws Websocket session initialization failed: Application error: undefined method `protocol' for nil:NilClass
```

**Comment by subhashsaran** [comment]
Ahh, Figured it out. issue turned out to be because we are using lograge in production which override action cable connection handler. I think anycable override somehow leave websocket to `nil`.
https://github.com/roidrage/lograge/blob/master/lib/lograge/rails_ext/action_cable/connection/base.rb#L8

**Comment by palkan** [comment]
Yep, that’s a lograge issue: https://github.com/roidrage/lograge/pull/257#issuecomment-525690256

Will add it to Troubleshooting.

**Comment by brunoalano** [comment]
Please, display a information about this on frontpage or some wiki.

**Comment by jsierles** [comment]
How are people solving this besides avoiding using lograge?

**Comment by palkan** [comment]
> How are people solving this besides avoiding using lograge?

The best way is to fork lograge and fix the way they do the monkey-patching. For example, for connection:

```ruby
module ConnectionInstrumentation
  def handle_open
    ActiveSupport::Notifications.instrument('connect.action_cable', notification_payload('connect')) { super }
  end

  def handle_close
    ActiveSupport::Notifications.instrument('disconnect.action_cable', notification_payload('disconnect')) { yield }
  end
  
  def notification_payload(method_name)
    { connection_class: self.class.name, action: method_name, data: request.params }
  end
end

# Somewhere in initializer

# Rails 6 added load hooks for ActionCable
ActiveSupport.on_load(:action_cable_connection) do
  prepend ConnectionInstrumentation
end

# In Rails <6
ActionCable::Connection::Base.prepend ConnectionInstrumentation
```

Or if you don't like forking, add the patch above to your codebase and load lograge the way it doesn't add its ActionCable patches.

For that, you need to load lograge before ActionCable, i.e.:

```ruby
# application.rb

require "action_controller/railtie"
# ...
require "lograge"
# only after that require ActionCable
require "action_cable/railtie"

# now we need to do some lograge setup manually

# extend base class (whatever it is), see https://github.com/roidrage/lograge/pull/257/files#diff-4b5bc970126e1c06601843417189f677R171

Lograge.extend_base_class(ActionCable::Channel::Base)

# subscribe to AC instrumentation
Lograge.attach_to_action_cable

# load server patches, see https://github.com/roidrage/lograge/pull/257/files#diff-4b5bc970126e1c06601843417189f677R205
require 'lograge/rails_ext/action_cable/server/base'
```

**Comment by palkan** [comment]
This PR provides a fix: https://github.com/roidrage/lograge/issues/304

**Comment by leoc** [comment]
Thank you @palkan!

I had to use `super` for closing connections, otherwise it complained about no block given for `yield`:

```ruby
#  config/lograge_fix/lograge/rails_ext/action_cable/connection/base.rb 
module Lograge
  module ActionCable
    module ConnectionInstrumentation
      def handle_open
        ActiveSupport::Notifications.instrument("connect.action_cable", notification_payload("connect")) { super }
      end

      def handle_close
        ActiveSupport::Notifications.instrument("disconnect.action_cable", notification_payload("disconnect")) { super }
      end

      def notification_payload(method_name)
        {connection_class: self.class.name, action: method_name, data: request.params}
      end
    end
  end
end

ActionCable::Connection::Base.prepend(Lograge::ActionCable::ConnectionInstrumentation)
```

**Comment by palkan** [comment]
Yeah, I've updated the PR, so you can use my fork instead of a patch.

**Comment by ryansch** [comment]
@palkan I just hit this today and found your fixed version in https://github.com/roidrage/lograge/pull/310. Thanks!!
