### ISSUE TITLE
anycable.yml or cable.yml

### ISSUE THREAD

**Issue by christianvargasforero** [anycable/anycable-rails#107]
Hello, my question is simple, do I use only anycable.yml  or cable.yml or should I use both files? Thank you

**#anycable.yml**
default:&default
  rpc_host: "localhost:50051"
  log_grpc: false
  log_file: nil
  debug: false # Shortcut to enable GRPC logging and debug level
  log_level: info
  redis_channel: "____anycable____"
  redis_url: "redis://localhost:6379"
  redis_sentinels: []
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default`

**#cable.yml** 
development:
  adapter: redis
  url: redis://localhost:6379/1 
test:
  adapter: async
production:
  adapter: any_cable
  url: redis://localhost:6379
  channel_prefix: ____anycable____

**Comment by palkan** [comment]
> do I use only anycable.yml or cable.yml or should I use both files? 

You should use both.
`cable.yml` is a configuration for Action Cable framework; there we only need to set the `any_cable` adapter.

`anycable.yml` defines AnyCable configuration.
