### ISSUE TITLE
Reduce gem weight

### ISSUE THREAD

**Issue by seanfcarroll** [anycable/anycable-rails#109]
Anycable is a great library, but it is using quite a lot of memory.

### Tell us about your environment

**Ruby version:**
2.6
**Rails version:**
5.2
**`anycable` gem version:**
0.6.3
**`anycable-rails` gem version:**
0.6.4

### What did you do?

Installed the [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) gem, and then ran the benchmarks.

```
bundle exec derailed bundle:mem
```

### What actually happened?

```
 anycable-rails: 4.5625 MiB
    anycable/rails: 4.5586 MiB
      anycable: 3.4219 MiB
        anycable/server: 2.2656 MiB
          anycable/health_server: 1.7969 MiB
```

**Comment by palkan** [comment]
Let's take a look deeper:

```
anycable-rails: 5.9375 MiB
    anycable/rails: 5.9375 MiB
      anycable: 5.9375 MiB
        anycable/server: 3.3008 MiB
          anycable/health_server: 1.8008 MiB
            webrick: 1.543 MiB
          grpc/health/checker: 1.2422 MiB
            grpc/health/v1/health_services_pb: 1.2422 MiB (Also required by: anycable/server)
              grpc/health/v1/health_pb: 1.2422 MiB
                google/protobuf: 0.9844 MiB (Also required by: anycable/rpc/rpc_pb)
        anycable/middleware_chain: 2.6367 MiB
          anycable/middleware: 2.6367 MiB
            grpc: 2.6367 MiB (Also required by: anycable/server, grpc/health/checker, and 3 others)
```

That could be translated into:

`anycable-rails` ~ `anycable` ~ `grpc` + `protobuf` + `webrick`.

The only optional component here is Webrick. So, we can save about 20% by making it loaded conditionally (see https://github.com/anycable/anycable/pull/94).
