### ISSUE TITLE
Heroku Doc difference

### ISSUE THREAD

**Issue by kwent** [anycable/anycable-rails#112]
Documentation

- https://github.com/anycable/anycable/wiki/Heroku-Deployment (old)
- https://docs.anycable.io/#/deployment/heroku (new)

Let's delete the article in the wiki. It's referenced in google first and i wasted time setting it up the old way.

Regards

**Comment by palkan** [comment]
Makes sense. Dropped the while Wiki!

**Comment by palkan** [comment]
@kwent If you need any help with making AnyCable up and running, feel free to ping me (or anyone at @evilmartians).
