### ISSUE TITLE
Restore original client IP through the headers

### ISSUE THREAD

**Issue by vitobotta** [anycable/anycable-rails#118]
Hi,

### Tell us about your environment

**Ruby version:**
2.6.5

**Rails version:**
6.0.2

**`anycable` gem version:**
0.6.4

**`anycable-rails` gem version:**
0.6.5

**`grpc` gem version:**
1.27.0-x86_64-linux

### What did you do?
I have a whitelist in my app that allows access when a specific domain is used, only to some specific IP addresses. So when I use the app with that domain, the request.remote_ip is used to determine whether to grant or deny access.

Unfortunately the RPC server says that the connection attempt is unauthorized, and I suspect that it is because the IP address seen by the RPC server is wrong. Is this possible? The headers that the RPC sees include the REMOTE_ADDR header, but that is set to the IP of the load balancer, so my "firewall" in the app will deny access. The headers seen by RPC do not include other headers like RPC see all the headers passed by Nginx?

### What did you expect to happen?
I would expect the RPC to see the correct IP of the client when the app is behind a load balancer.

### What actually happened?
The connections are rejected and I think it may be because the IP seen by the RPC is that of the load balancer, so access is denied by my app firewall.

Thanks in advance for any help!

**Comment by vitobotta** [comment]
I've added  the x-forwarded-for header to anycable-go and I can see that header, but I still get connections rejected.  This is my connection.rb

```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    private

      def find_verified_user
        env['rack.session'] = cookies.encrypted[Rails.application.config.session_options[:key] || raise("No cookies key in config")]

        warden = Warden::SessionSerializer.new(env)


        if verified_user = warden.fetch(:user)
          verified_user
        else
          reject_unauthorized_connection
        end
      end
  end
end
```

**Comment by vitobotta** [comment]
Uhm I don't think it's the IP. There is something weird going on... I am using Okteto for development and when Okteto is up, the authentication with the Devise/Warden cookie works. When Okteto is down and the normal deployment is working, the connection is rejected even though the cookie is seen by the RPC. Arghh

**Comment by palkan** [comment]
>  the normal deployment is working

What is the normal deployment?

> the connection is rejected even though the cookie is seen by the RPC

Maybe, something wrong with the session.

What do you think about trying the upcoming v1.0 which has a built-in support for sessions and much better Warden integration? (See https://github.com/anycable/anycable-rails/pull/111).

The `1.0.0.preview1` release is out (for both `anycable-rails` and `anycable-go`), the final release is coming in ~1-2 months, but we're already using it in one of our projects. Since you're just starting experimenting with cables, it makes sense to use the edge version.

**Comment by vitobotta** [comment]
Hi @palkan, by normal deployment I mean the deployment with Okteto disabled. But I have uninstalled the app, deleted the namespace, and redeployed without running Okteto, and I have the same problem. I have no idea why it worked when Okteto was activated.... but now I have the app redeployed from scratch and web sockets connections are still refused even though the RPC sees the session cookie (I can see it in the logs). 

I will try your suggestion right away, thanks!

**Comment by vitobotta** [comment]
@palkan I have changed both the image tag and the gem, and redeployed. It doesn't show connection attempts etc now in the RPC logs? Has some setting changed for the logs?

**Comment by vitobotta** [comment]
From https://github.com/anycable/anycable-rails/blob/1.0-dev/lib/anycable/rails/config.rb it seems that the `access_logs_disabled` setting is now ignored?

**Comment by palkan** [comment]
> it seems that the access_logs_disabled setting is now ignored?

It means that you  cannot provide it as a CLI option, but you can set in in `anycable.yml`. So, it works as [before](https://github.com/anycable/anycable-rails/blob/v0.6.5/lib/anycable/rails/config.rb).

**Comment by vitobotta** [comment]
I do have it in the yaml file though

**Comment by vitobotta** [comment]
@palkan  Besides the logging, how do I change the code above to use the newly available session with Devise, to check if the user is authenticated?

**Comment by vitobotta** [comment]
Oh, in the anycable go logs I see this with the new image:

```
Websocket session initialization failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.43.181.177:50051: connect: connection refused"
```

**Comment by vitobotta** [comment]
I had to set rpc_host explicitly. It looks like that has changed? With the new version of the gem it was binding to 127.0.0.1

**Comment by vitobotta** [comment]
I can't figure it out... when the up is running with Okteto up, authentication works. When deployment is running normally - without Okteto - session is nil. Same thing with the version you suggested.

**Comment by palkan** [comment]
> I had to set rpc_host explicitly. It looks like that has changed? 

Yep, there are some changes in v1.0. Here is a WIP upgrade notes: https://github.com/anycable/docs.anycable.io/blob/v1.0/docs/v1/upgrade-notes/0_6_0_to_1_0_0.md

> when the up is running with Okteto up, authentication works. When deployment is running normally - without Okteto - session is nil

TBH, I have no idea what Okteto is 🙂 @Envek maybe, you heard about it?

What session store do you use? Cookies? For the sake of the experiment, could you try to use Redis for session (or if you're already using Redis switch to cookies—I want to check whether the problem has something with a particular session store).

**Comment by vitobotta** [comment]
Hi @palkan I am using Cookie store with `domain: :all`, so that the cookies can be shared between app.domain.com and ws.domain.com (which is the domain for AnyCable). Are there any issues if I use a different domain for AnyCable?  Also, anycable-go is passing the origin header HTTP_ORIGIN but it's set to app.domain.com, not ws.domain.com. Can this cause issues? I tried that code for Devise in an initializer but there is no difference. It looks like the session is not loaded: `ActionDispatch::Request::Session:0x7f1675097968 not yet loaded`.

**Comment by palkan** [comment]
> ActionDispatch::Request::Session:0x7f1675097968 not yet loaded.

Session is loaded lazily if you try to access some value. Do you use JS client loaded on some Rails-backed HTML page? If so, try to add some value to the session in the application controller (`session[:test] = 123`) and check its value in the connection.

> Also, anycable-go is passing the origin header HTTP_ORIGIN but it's set to app.domain.com, not ws.domain.com. Can this cause issues?

Does it depend on whether you use Okteto or not? We're definitely looking for something that differs in these two cases.

**Comment by vitobotta** [comment]
I have reproduced the issue with Okteto as well so finally I can investigate without redeploying all the time. Okteto basically lets me code locally while the containers run in my Kubernetes cluster. So when it's activated, I can run the image with a custom command, bash, so I can use the shell as if it was local.  Where should I actually put the following block?

```
AnyCable::Rails::Rack.middleware.use Warden::Manager do |config|
  Devise.warden_config = config
end
```

I've tried both in an initializer and in the connection.rb

**Comment by vitobotta** [comment]
Also, with that code, how do I get the Devise/Warden user?

**Comment by palkan** [comment]
> I've tried both in an initializer and in the connection.rb

Initializer.

> Also, with that code, how do I get the Devise/Warden user?

`env["warden"].user`

**Comment by vitobotta** [comment]
I tried that, and no change. `env["warden"]` is nil, `env["warden"]` returns:

```
Warden::Proxy:70176872849800 @config={:default_scope=>:default, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>true}
```

Also I added that code to an initializer like this: 

```
AnyCable::Rails::Rack.middleware.use Warden::Manager do |config|
p  Devise.warden_config = config
end
```

Nothing is printed.

**Comment by palkan** [comment]
If `env["warden"]` return a `Warden::Proxy` then initializer is correct (I think, the block is evaluated during the request, not immediately).

Does `env["warden"].user` returns a user when Okteto is up?

**Comment by vitobotta** [comment]
LOL now it happens with Okteto too after all these changes :D But I am happy about it, so I can find a way that works with and without Okteto.  `env["warden"].user` returns nil in any case now. Could it be the different domains? With the Rack changes in 1.0, is the `domain: :all` setting respected? But I see the cookie in the logs....

**Comment by vitobotta** [comment]
Progress! Seems like `env["action_dispatch.request.unsigned_session_cookie"]` contains some warden data, both the session id and `warden.user.user.key` has a value. How can I extract the user from that?

**Comment by vitobotta** [comment]
I was in Okteto when I got that value... :(

**Comment by vitobotta** [comment]
@palkan how are the cookies passed to the RPC process from AnyCable-Go?

**Comment by vitobotta** [comment]
I am trying some old workaround I found about Warden and ActionCable, where Warden sets a user_id cookie when it sets the user. The RPC process does see this cookie and I am able to fetch the user by ID from the database instead of getting it from Warden (since it's nil). However it works only with plain cookies but not cookies.encrypted. The RPC process sees the cookie in the cookies collection only, even though it's set with cookies.encrypted. The cookie is still encrypted though... I am trying to find how to decrypt it manually..

**Comment by sponomarev** [comment]
@vitobotta 

> how are the cookies passed to the RPC process from AnyCable-Go?

They are passed with headers by default or explicitly with `--headers`  option or `ANYCABLE_HEADERS` env variable. See https://docs.anycable.io/#/anycable-go/getting_started?id=configuration-parameters

**Comment by vitobotta** [comment]
Yeah I do I have "cookie" in the header. Why can't I read encrypted cookies?

**Comment by vitobotta** [comment]
@palkan I tried switching to Redis for the session store as you suggested earlier and it works!!! It works both with and without Okteto. I have no idea of how, but Okteto triggers something that makes the behaviour of AnyCable with cookies session store differ between when it's up and running.

`env["warden"].user` is still nil, but I got it working with:

```
      def find_verified_user
        warden = Warden::SessionSerializer.new(env)

        if verified_user = warden.fetch(:user)
          verified_user
        else
          reject_unauthorized_connection
        end
      end
```

I can't believe it... I should have tried Redis earlier. What could be causing these issues with the cookies session store? Thanks!

**Comment by palkan** [comment]
> What could be causing these issues with the cookies session store?

Try checking `RAILS_ENV` and `secret_key_base`; you mentioned that you're using encrypted cookies; maybe, they failed to decrypt. 

> env["warden"].user is still nil, but I got it working with:

Interesting. What is the value of `Devise.warden_config.default_scope`? (in both AnyCable and Rails server).

Try using `env["warden"].user(:user)`. That should work (it does the same thing with SessionSerializer under the hood).

**Comment by vitobotta** [comment]
RAILS_ENV and the secret_key_base are OK. I tried several times decrypting with no success. But I can fetch the user from Warden now, so that's a lot better I think. `env["warden"].user` was always nil so I doubt I could get something with `env["warden"].user(:user)` but I'll have a look. Thanks

**Comment by vitobotta** [comment]
Hey @palkan , it looks like `env["warden"].user(:user)` works as well. How come, if `env["warden"].user` is nil? Weird.  I must be missing something obvious :D

So I seem to be able to move on now, using the Redis session store. Should we close this or keep it open as a reminder to look into weirdness with the Cookie session store? Thanks a lot for your help!

**Comment by Envek** [comment]
`env["warden"].user(:user)` is a function call with one argument and `env["warden"].user` is also function call but without arguments. It is `env["warden"].user()` actually. And it returns `nil` (and I don't know why)

**Comment by vitobotta** [comment]
@Envek oh it makes sense. I knew it was something obvious. I should have checked the code. Thanks!
