### ISSUE TITLE
How to get connected channels to redis?

### ISSUE THREAD

**Issue by kesha-antonov** [anycable/anycable-rails#12]
Hello again! @palkan 

Last question of migration from ActionCable to AnyCable.

I have this code:
```
ActionCable.server.pubsub.redis_connection_for_subscriptions.pubsub('channels', "SomeChannel_#{type}_#{id}_*").each do |channel|
  ActionCable.server.broadcast(channel, data)
end
```

And now I have exception: 
```
NoMethodError: undefined method `redis_connection_for_subscriptions' for #<Anycable::PubSub:0x00563a0ab8e288>
```

I used that code to detect connected clients and send notifications only to them.

I've tried to use ```ActionCable.server.pubsub.redis_conn.pubsub('channels', '...')```. But only thing I can return is ['anycable']

What code should I use now?

Thanks!

**Comment by kesha-antonov** [comment]
AnyCable: https://github.com/anycable/anycable/blob/master/lib/anycable/pubsub.rb
ActionCable:
https://github.com/rails/rails/blob/934327e14ee107d531c8a48e297f74a5cd5eb8bb/actioncable/lib/action_cable/subscription_adapter/redis.rb#L41

**Comment by palkan** [comment]
Wow, interesting.. But, unfortunately, it can be done with AnyCable. AnyCable doesn't store any information about channels in Redis, it uses only as _internal_ transport.

And it's actually not the part of a public Action Cable API (and it's event against the PubSub philosophy – you  shouldn't anything about the end users, just send messages into channels).

> I used that code to detect connected clients and send notifications only to them.

Why not subscribing all connections to the same stream then? Like `stream_from "all"` somewhere in your channel code (or event using a specific channel for that).

**Comment by kesha-antonov** [comment]
@palkan 
Use case:

1) We have a page in which people can leave comments
2) Anybody can join this page
3) BUT we need to send "customized" data to different people

Hence user A will connect to channel with "page_1_A" 
user B will connect to that channel with "page_1_B"

So this is needed to send "customized" data to different people

**Comment by kesha-antonov** [comment]
So list of channels is unknown. We know only template of channel names

Maybe there is another way?

**Comment by kesha-antonov** [comment]
With code above I've used this method of Redis: https://github.com/redis/redis-rb/blob/master/lib/redis.rb#L2217

To get channels.

Now it returns only ['anycable']

**Comment by kesha-antonov** [comment]
Maybe I said it wrong.
I'm trying to get list of "active" channels. Which we created with "stream_from(...)"

**Comment by palkan** [comment]
Well, I have to say that it's impossible out-of-the-box with AnyCable. There is no a way to _ask_ AnyCable about anything (including the list of active streams).

On the other hand, I'd suggest to avoid Action Cable hacking too (i.e. accessing hidden internals, such as channels list) and implement streams tracking manually.  For example, using Redis and subscription callbacks:

```ruby
# pseudo-code
class PresenceTracker
  def self.page_users(page)
     redis.smembers(page)
  end
  
  def self.track(page, user_id)
     redis.sadd(page, user_id)
  end

  def self.untrack(page, user_id)
    redis.srem(page, user_id)
  end
end

class MyChannel < ApplicationCable::Channel
  after_subscribed :track_user
  after_unsubscribed :untrack_user

  def track_user
     PresenceTracker.track(params[:page], current_user.id)
  end

   def untrack_user
     PresenceTracker.untrack(params[:page], current_user.id)
  end
end

PresenceTracker.page_users("page_A").each { |user_id| ActionCable.broadcast("page_A_#{user_id}", ...)  }
```

Smth like that (but we have to deal with possible race conditions in Redis).

**Comment by kesha-antonov** [comment]
Thanks a lot! @palkan 

I've listened to your suggestion and refactor to single "stream_from".

Yes, this code might work!
I'll try to be on "safe-side" for now. Thanks again!

**Comment by BlockerCambodia** [comment]
😍😍
