### ISSUE TITLE
Multiple replicas to avoid downtime

### ISSUE THREAD

**Issue by vitobotta** [anycable/anycable-rails#120]
Hi, to avoid downtime in production, I was thinking to have a couple of replicas (in Kubernetes) for both the Go server and the RPC server, with rolling strategy. But web sockets are persistent connections, so what happens during the time the replica a client is connected to is terminated? I guess the client will reconnect quickly to the a replica but can messages be lost in the meantime or are they kinda queued in Redis, so they will be received anyway by the client? Thanks!

**Comment by Envek** [comment]
Websocket connections are being kept by anycable-go. So you want to restart it as rarely as possible (only when you want to upgrade anycable-go itself or change anycable settings).

In case of using [our Helm chart](https://helm.anycable.io), you don't have to do anything special: if nothing changes in anycable-go related `values` then it won't restart.

Messages sent in meantime when clients are reconnecting will be lost: there is no queuing in Redis Pub/Sub and no mechanisms built in Action Cable protocol. If you need durable message delivery you have to build it yourself.

RPC server is safe to restart as there is no persistent connection between anycable-go and RPC. And actually you want to restart it on every deploy to update your application code.

Just ensure that you always have running some instances of it, e.g. with following K8s Deployment configuration:

```yaml
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
```

Check our brand new [manual on deploying to Kubernetes](https://docs.anycable.io/#/deployment/kubernetes) for details.

**Comment by vitobotta** [comment]
Gotcha, thanks!
