### ISSUE TITLE
Stable 1.0 version release date for anycable-rails and anycable-go ??

### ISSUE THREAD

**Issue by SakthiGurunathan07** [anycable/anycable-rails#122]
We are trying to migrate from Action Cable to AnyCable as we need to scale our product to support 20k connections. We faced a couple of issues in anycable-rails 0.6.5 and anycable-g0 0.6.4 versions
1. Broadcasting was not working inside delayed jobs (asynchronous jobs).
2. We frequently face this below error **“Perform error: rpc error: code = ResourceExhausted desc = No free threads in thread pool”** 
Both the issues were fixed in anycable-rails 1.0.0 preview and anycable-go 1.0.0preview versions.

But we do see a slight memory increase in anycable-go 1.0.0 process when we do a load test with anycable-rails 1.0.0 compared to anycable-go 1.0.0 with anycable-rails 0.6.5. But we could see anycable-rails 1.0.0 handle more requests than anycable-rails 0.6.5.

As we are planning to use Anycable in production, can we know the stable version release date for 1.0 preview versions?

Also one more doubt, do we need multiple anycable- Go servers and Anycable rails servers to be started to handle more load or just 1 each should be sufficient? What will be right architecture ? Do we have any recommendations like till what load we should use 1 anycable-go server and 1 anycable-rails server ?

@palkan

**Comment by palkan** [comment]
> But we do see a slight memory increase in anycable-go 1.0.0 process when we do a load test with anycable-rails 1.0.0 compared to anycable-go 1.0.0 with anycable-rails 0.6.5. But we could see anycable-rails 1.0.0 handle more requests than anycable-rails 0.6.5.

Both insights are very interesting. Could you please provide some numbers?

> Do we have any recommendations like till what load we should use 1 anycable-go server and 1 anycable-rails server ?

Highly depends on the business-logic. How complex are your channels? What is the mean/95p command duration?

With anycable-go 1.0.0, you can use `rpc_retries_num` metrics to determine whether you need more RPC servers: if this number seems high (it should not be always zero, but not that big, maybe, 5-10% of total RPC calls is a threshold).

From the anycable-go point of view, you're mostly limited by memory.

There is also a reason to have at least two RPC servers: for performing rolling updates. That is, you have one anycable-go server, RPC load balancer (e.g., Envoy) and a few RPC servers. When you deploy the application, you only update RPC servers (in most situation you can keep anycable-go running and connections persistent), one by one, without downtime.

The final version 1.0.0 is planned for late-April — early-May. RC1 is planned for mid-April (that means that all the desired features should be implemented, WIP documentation is published, minor features are on their way).

**Comment by SakthiGurunathan07** [comment]
Thanks @palkan  for providing the stable version release dates and it will be really helpful.
> Both insights are very interesting. Could you please provide some numbers?

Please find the numbers in the link. I could see a good decrease in CPU usage with anycable 1.0.0 but memory got increased compared to anycable 0.6.5.
[https://tinyurl.com/sdjdjp9](url)

> Highly depends on the business-logic. How complex are your channels? What is the mean/95p command duration?

We are expecting 20k connections at any point of time. Please find the benchmarks below. I don'
t know how to interpret these metrics, documentation would help here.

**With 10k connections:**

broadcast_msg_total=1858 broadcast_streams_num=1 client_msg_total=58197 clients_num=0 clients_uniq_num=0 context=metrics disconnect_queue_size=0 failed_auths_total=0 failed_broadcast_msg_total=0 failed_client_msg_total=0 goroutines_num=15 mem_sys_bytes=638472440 rpc_call_total=78197 rpc_error_total=0 rpc_retries_total=3


**With 20k connections:**

broadcast_msg_total=10258 broadcast_streams_num=1 client_msg_total=118143 clients_num=0 clients_uniq_num=0 context=metrics disconnect_queue_size=0 failed_auths_total=0 failed_broadcast_msg_total=0 failed_client_msg_total=0 goroutines_num=15 mem_sys_bytes=1204937976 rpc_call_total=158143 rpc_error_total=0 rpc_retries_total=0

Thanks for your insights on the RPC load balancer. Could you please help me understand why we don't need multiple Go servers? Also, I could see the memory was accumulated for Go server and it was released only on the Go server restart.
Do we have any benchmarks or supported limits for a single go server ? Also, instead of Envoy can we use NGNIX for RPC load-balancing?

Just asking this out of curiosity and this question is not related with anycable. Do you have any suggestions/architecture with respect to database for 20k concurrent sessions and assuming each person sending message with a interval of 5 seconds. Currently we are using MYSQL. Whether MYSQL is right database ?

**Comment by chronustdd** [comment]
@palkan  Any updates on the release date for the final 1.0.0 version for anycable-go and anycable-rails ?

**Comment by SakthiGurunathan07** [comment]
@palkan Any updates on the release date for the final 1.0.0 version for anycable-go and anycable-rails ?

**Comment by palkan** [comment]
1.0.0 is out: https://docs.anycable.io/v1/#/release_notes
