### ISSUE TITLE
Can't access encrypted or signed cookies

### ISSUE THREAD

**Issue by pbhogan** [anycable/anycable-rails#125]
rails (6.0.2.2)
anycable (1.0.0.preview2)
anycable-rails (1.0.0.preview2)

Rails and anycable-go are running on the same domain (localhost) in docker containers, along with the accompanying anycable rpc server and redis requirements. Everything works, as far as sending messages is concerned.

**The problem:**
In ApplicationCable::Connection#connect I'm unable to access any encrypted cookies... or rather, they won't decrypt and I can't figure out why.

I started by trying to access the session cookie (I did set `domain: :all` on the session store). It just returns `nil`, although accessing the unencrypted cookie shows the encrypted data.

To simplify the problem a bit, I tried just setting a simple encrypted cookie in ApplicationController like so:
```
cookies.encrypted[:test] = { value: "12345", domain: :all }
```

Back in cable-land, accessing `cookies[:test]` gives back the encrypted data, but `cookies.encrypted[:test]` returns `nil`. So decryption is failing.

A bit of debugging and `Rails.application.secret_key_base`, cookie serializer and other relevant variables do appear to be set, and are identical to what the values are in `ApplicationController`.

Digging into the rails [codebase](https://github.com/rails/rails/blob/5debcecdf106051453300c7002cdd5cef3c27cf0/actionpack/lib/action_dispatch/middleware/cookies.rb#L620) a bit, I tried manually decoding the encrypted cookie value:

```
encrypted_cookie_cipher = request.encrypted_cookie_cipher || "aes-256-gcm"
signed_cookie_digest = request.signed_cookie_digest || "SHA1"
key_len = ActiveSupport::MessageEncryptor.key_len(encrypted_cookie_cipher)
secret = request.key_generator.generate_key(request.authenticated_encrypted_cookie_salt, key_len)
encryptor = ActiveSupport::MessageEncryptor.new(secret, cipher: encrypted_cookie_cipher, serializer: ActionDispatch::Cookies::JsonSerializer)
encryptor.decrypt_and_verify(cookies[:test])
```

This raises `ActiveSupport::MessageEncryptor::InvalidMessage`. 

This exception is what is being hit by `cookies.encrypted[:test]` which has a [`rescue`](https://github.com/rails/rails/blob/5debcecdf106051453300c7002cdd5cef3c27cf0/actionpack/lib/action_dispatch/middleware/cookies.rb#L661) that returns `nil`. I further confirmed this is what is happening by monkey patching rails.

At this point I'm out of my depth.

What am I doing wrong? Why can't cookies be decrypted? What have I missed? Is there something else in the rails environment that is not in the cable environment?

**Comment by palkan** [comment]
I've checked both encrypted and signed cookies in the demo app (https://github.com/anycable/anycable_demo/tree/try/encrypted-cookies)—both works.

One guess is the environment. Do you have `RAILS_ENV=development` set for RPC?

**Comment by pbhogan** [comment]
I have no environment set so it's in development mode but so is my rails app. I checked by debugging Rails.env in both. Shouldn't they be the same? I do something similar to the docker-compose file in your demo app where the rpc server inherits from the same definition as the rails service.

**Comment by palkan** [comment]
> Shouldn't they be the same?

They should.

`cookies[:test]` is the same in RPC and Web servers?

And, just to confirm, you set `secret_key_base` explicitly in development (i.e., not auto-generated)? What if you try to set it right the the `config/environment/development.rb` as a plain text?

**Comment by pbhogan** [comment]
Ah! That was it. I wasn't aware `secret_key_base` was being generated by default in development. All of my existing projects are older so either use secrets.yml or predate that.

It's a pity that rails generates it based on the application class name, which I guess is different when AnyCable loads up the environment, rather than basing it on something more static. And it doesn't use the environment variable either.

Thanks—at least I can make it work now!
