### ISSUE TITLE
Anycable Generator could not be found

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable-rails#130]
Greetings, I am using anycable 0.6.5/anycable-rails 0.6.5 and my ruby version is 2.6.3. I cannot run the generator for anycable setup, I receive **Could not find generator 'anycable:setup'**

**Comment by palkan** [comment]
The generator is only available in `anycable-rails` >= 1.0.0 (which is currently a pre-release). Upgrade to `gem "anycable-rails", "1.0.0.rc1"`.
