### ISSUE TITLE
Incompatible AnyCable RPC client

### ISSUE THREAD

**Issue by iHiD** [anycable/anycable-rails#132]
### Tell us about your environment

**Ruby version:** ruby 2.6.6p146

**Rails version:** 6.1.0.alpha

**`anycable` gem version:** 1.0.0.rc1

**`anycable-rails` gem version:** 1.0.0.rc2

**`grpc` gem version:** 1.28.0

### What did you do?

Hello. First time user of anycable.

I've installed `anycable-rails` 1.0.0rc2 and run the setup generator. 

When I run a Procfile I get an [Incompatible AnyCable RPC client](https://github.com/anycable/anycable/blob/master/lib/anycable/middlewares/check_version.rb#L18) error. I can't see any reference anywhere to `protov`. Should I be setting something?

Downgrading to 0.x release fixes this.

**Comment by Envek** [comment]
What version of [anycable-go](https://github.com/anycable/anycable-go) you're using?

Websocket server and Ruby client versions must match up to minor version (so, anycable-go 0.6.x should be used with anycable gem 0.6.x and anycable-go version 1.0.x must be used with anycable gem 1.0.x)

**Comment by Envek** [comment]
Most probably problem is that `rails g anycable:setup` installs older `1.0.0.preview1` version of anycable-go for you:
https://github.com/anycable/anycable-rails/blob/4366ef5f56d1e6879fe86a62c3bd56e10b7d9c9c/lib/generators/anycable/download/download_generator.rb#L12-L13
While [anycable-go 1.0.0.rc1](https://github.com/anycable/anycable-go/releases/tag/v1.0.0.rc1) is already released (and there were some big changes between them)

**Comment by palkan** [comment]
> Websocket server and Ruby client versions must match up to minor version

Not exactly. AnyCable-Go v1.0 is backward-compatible with AnyCable RPC v0.6.

Speaking about the issue, I believe the problem is with the outdated `anycable-go` (@iHiD or you using a different server implementation?)

**Comment by iHiD** [comment]
Hello. Thanks for following up.

I installed `anycable-go` via homebrew (as per the [instructions in the setup script](https://github.com/anycable/anycable-rails/blob/4366ef5f56d1e6879fe86a62c3bd56e10b7d9c9c/lib/generators/anycable/setup/setup_generator.rb#L243)). It has installed `0.6.5`.

**Comment by palkan** [comment]
Got it. Since we're still in RC phase, setup script could be out-of-sync. Sorry for that.

You can install `anycable-go` 1.0.0.rc1 by running `brew install --HEAD anycable-go`.

**Comment by iHiD** [comment]
Great. Thanks! :) 

Yeah - it's no worries at all. Downgrading worked. I just figured it might be useful feedback in case it's a rc1 issue that needs fixing before release etc (which I understand it's not actually :))
