### ISSUE TITLE
Heroku, SECRET_KEY_BASE and cookie encryption/decryption

### ISSUE THREAD

**Issue by mrrooijen** [anycable/anycable-rails#135]
Hi,

This problem has already been resolved, but I thought I'd just open an issue here in case someone else runs into this.

I've attempted to deploy an application to Heroku along with AnyCable. I was able to get the ws/grpc server to access the cookie that was set by the primary server, but it wouldn't properly decrypt it on the ws/grpc server.

The `Rails.application.credentials.secret_key_base` value was identical between the two servers. However, they for some reason both had a different `Rails.application.secret_key_base`. My Heroku environment variables (`$ heroku config`) also didn't contain the `$SECRET_KEY_BASE`. Yet, from the shell (`$ heroku run 'echo $SECRET_KEY_BASE'`) the `$SECRET_KEY_BASE` environment variable was set and returned a key, but it differed from the value defined in `config/credentials/production.yml.enc`.

It turns out, to my surprise, that this environment variable defaults to a static value by Heroku when you don't define it yourself.

```
$ heroku run cat .profile.d/ruby.sh
# ...
export SECRET_KEY_BASE=${SECRET_KEY_BASE:-34154c39c274de1b2366ccb564c6542f4268e9f4f7e9f1354cacb0b39169deb7484bd934577edb1d049c7012077ad80427192489617409933e2be98df784d9fd}
# ...
````

This seems counterintuitive to me considering the fact because of this your application will never pick up `secret_key_base` from your credentials file unless you explicitly set `ENV["SECRET_KEY_BASE"]` to `nil` in `config/environment.rb`.

Setting `ENV["SECRET_KEY_BASE"]` to `nil` resolved the issue. Merely removing it with `$ heroku config:remove SECRET_KEY_BASE` isn't enough.

(Might be worth also adding this to troubleshooting.)

**Comment by palkan** [comment]
Thanks for posting this!

Lined this issue to the related troubleshooting section: https://docs.anycable.io/#/v1/troubleshooting?id=authentication-fails-with-undefined-method-39protocol39-for-nilnilclass

**Comment by mrrooijen** [comment]
👍 Thanks for AnyCable!

**Comment by armiiller** [comment]
Another upvote here - Many managed service providers like Heroku (and in my case Fly.io) will set the `SECRET_KEY_BASE` for the production environment for your "web" app. When you stand up your RPC server this is usually not set. Make sure to find what's in the "web" app and set that on your RPC app.

Spent too much time on this... :/
