### ISSUE TITLE
Websocket session initialization failed: Application error: undefined method `call' for ApplicationCable::Connection:Class

### ISSUE THREAD

**Issue by prwhitehead** [anycable/anycable-rails#137]
### Tell us about your environment

**Ruby version:** 2.6.6

**Rails version:** 6.0.3.2

**`anycable` gem version:** 1.0.1

**`anycable-rails` gem version:** 1.0.1

**`grpc` gem version:** 1.17

### What did you do?

Created a docker based rails app with working ActionCable using Redis adaptor, then tried to add in AnyCable. 

### What did you expect to happen?

The connections would be successful

### What actually happened?

The connections were not successful. 

==========================================================================================

Hello, i've been trying to get an app up and running inside Docker using AnyCable from the very start. Everything works fine using the redis adaoptor, I am able trigger boardcast events and see them received by the channel subscriber. However with AnyCable, I am having issues configuring it. 

The `development.rb` is set to correctly as far as I can see and AnyCable::Rails is enabled: 

    irb(main):001:0> AnyCable::Rails.enabled?
     => true

    config.action_cable.url = ActionCable.server.config.url = ENV.fetch("CABLE_URL", "ws://localhost:8080/cable")

`cable.yml` is as follows and `ACTION_CABLE_ADAPTER` is set to `any_cable` in the docker-compose variables: 

     development:
          adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "redis") %>

`anycable.yml` is set to the installed defaults: 

    default: &default
      # Turn on/off access logs ("Started..." and "Finished...")
      access_logs_disabled: false
      # Persist "dirty" session between RPC calls (might be required for apps using stimulus_reflex <3.0)
      # persistent_session_enabled: true
      # This is the host and the port to run AnyCable RPC server on.
      # You must configure your WebSocket server to connect to it, e.g.:
      #   $ anycable-go --rpc-host="<rpc hostname>:50051"
      rpc_host: "0.0.0.0:50051"
      # Whether to enable gRPC level logging or not
      log_grpc: false
      # Use Redis to broadcast messages to AnyCable server
      broadcast_adapter: redis
      # Use the same channel name for WebSocket server, e.g.:
      #   $ anycable-go --redis-channel="__anycable__"
      redis_channel: "__anycable__"
      # You can use REDIS_URL env var to configure Redis URL.
      # Localhost is used by default.

I was having issues with the Rails refusing the wc connection due to the `content_src` policy, but it is now: 

    policy.connect_src :self, :https, "http://localhost:3035", "ws://localhost:3035", 'ws://localhost:8080'

This is the logout from the connection. It seems to start fine, display no errors, but then throw `Websocket session initialization failed: Application error: undefined method `call' for ApplicationCable::Connection:Class`: 

    ws_1         | D 2020-08-25T20:56:22.960Z context=main 🔧 🔧 🔧 Debug mode is on 🔧 🔧 🔧
    ws_1         | I 2020-08-25T20:56:22.960Z context=main Starting AnyCable 1.0.1-1551caf (pid: 1, open file limit: 1048576)
    ws_1         | D 2020-08-25T20:56:22.960Z context=disconnector Calls rate: 10ms
    ws_1         | I 2020-08-25T20:56:22.961Z context=main Handle WebSocket connections at http://0.0.0.0:8080/cable
    ws_1         | I 2020-08-25T20:56:22.961Z context=main Handle health connections at http://0.0.0.0:8080/health
    ws_1         | I 2020-08-25T20:56:22.964Z context=rpc RPC controller initialized: anycable:50051 (concurrency: 28, proto_versions: v0,v1)
    ws_1         | D 2020-08-25T20:56:22.965Z context=http Starting WebSocket server at http://0.0.0.0:8080
    ws_1         | I 2020-08-25T20:56:22.995Z context=pubsub Subscribed to Redis channel: __anycable__

    anycable_1   | Starting AnyCable gRPC server (pid: 1, workers_num: 30)
    anycable_1   | AnyCable version: 1.0.1 (proto_version: v1)
    anycable_1   | gRPC version: 1.31.1
    anycable_1   | Serving Rails application from ./config/environment.rb
    anycable_1   | handling /anycable.RPC/Connect with #<Method: AnyCable::RPCHandler#connect>
    anycable_1   | handling /anycable.RPC/Command with #<Method: AnyCable::RPCHandler#command>
    anycable_1   | handling /anycable.RPC/Disconnect with #<Method: AnyCable::RPCHandler#disconnect>
    anycable_1   | handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check>
    anycable_1   | handling /grpc.health.v1.Health/Watch with #<Method: Grpc::Health::Checker(Grpc::Health::V1::Health::Service)#watch>
    anycable_1   | Broadcasting Redis channel: __anycable__
    anycable_1   | RPC server is starting...
    anycable_1   | RPC server is listening on 0.0.0.0:50051

    anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-08-25 20:59:07 +0000)
    anycable_1   | schedule another job
    anycable_1   | RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:8080/cable", headers:     {"cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVG86HVJhY2s6OlNlc3Npb246OlNlc3Npb25JZAY6D0BwdWJsaWNfaWRJIkUwNjUzY2Qz    NzcyOWJlODcwOWMyMjcyZmVkZDJmZjExZGUxNTg5MjY0YTlmNGFkYTk5MTFlOTIwYjRmZmNlMTkwBjsARkkiCWNzcmYGOwBGSSIxZHBwSFlkNk5OdTZ4UmRTamR6Q0FlZkV3S2pqclpNRTJJZD    ZlNjZYN0pIbz0GOwBG--a0b515448ac1e758011993a3118b3afc87b617fa; _session_id=f45cb426274ea5cb82a4ee0ea0b7b410", "REMOTE_ADDR"=>"172.22.0.1"}, cstate: {}, istate: {}>>
    ws_1         | D 2020-08-25T20:59:07.496Z context=rpc Authenticate response: error_msg:"undefined method `call' for ApplicationCable::Connection:Class"
    ws_1         | E 2020-08-25T20:59:07.496Z context=ws Websocket session initialization failed: Application error: undefined method `call' for ApplicationCable::Connection:Class
    anycable_1   | undefined method `call' for ApplicationCable::Connection:Class:
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:18:in `connect'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `call'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'

I've been reading as much as I can about how to set this up, however the failing connection seems to be outside of a simple configuration mistake. 

My (work in progress) `docker-compose.yml` incase thats of interest: 

    version: "3.3"

    services:
      app:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        ports:
          - 3000:3000
        volumes:
          - .:/app
        depends_on:
          - db
          - webpacker
        environment:
          ACTION_CABLE_ADAPTER: any_cable
          REDIS_URL: redis://redis:6379/0
          REDIS_SIDEKIQ_URL: redis://redis:6379/1
          CABLE_URL: ws://localhost:8080/cable
        stdin_open: true
        tty: true

     # ... truncated for brevity

      ws:
        image: anycable/anycable-go:1.0
        ports:
          - 8080:8080
        environment:
          ANYCABLE_HOST: 0.0.0.0
          ANYCABLE_REDIS_URL: redis://redis:6379/0
          ANYCABLE_RPC_HOST: anycable:50051
          ANYCABLE_DEBUG: 1
        depends_on:
          - redis

      anycable:
        build: .
        command: bundle exec anycable
        environment:
          REDIS_URL: redis://redis:6379/0
          WEBPACKER_DEV_SERVER_HOST: webpacker
          ANYCABLE_REDIS_URL: redis://redis:6379/0
          ANYCABLE_RPC_HOST: 0.0.0.0:50051
          ANYCABLE_DEBUG: 1
        ports:
          - 50051
        depends_on:
          - ws
          - redis

Thank you for the time you've put into this project. I've been super interested in it for a while. 
Paul.

**Comment by Envek** [comment]
Error is very similar to one discussed in #74. So it looks like that ActionCable adapter actually is **not** set properly in `config/cable.yml`. Check `ActionCable.server.config.cable` output in console.

You need to specify `ACTION_CABLE_ADAPTER` variable for `anycable` RPC process, not only for `app`. One method to do so is to reuse environment variables from `app` with [YAML anchors and aliases](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd), like this:

```yml
services:
  app:
    # …
    environment: &app_env
      ACTION_CABLE_ADAPTER: any_cable
      REDIS_URL: redis://redis:6379/0
      REDIS_SIDEKIQ_URL: redis://redis:6379/1
      CABLE_URL: ws://localhost:8080/cable
      ANYCABLE_REDIS_URL: redis://redis:6379/0

  anycable:
    # …
    environment:
      <<: *app_env
      ANYCABLE_DEBUG: 1
      # …
```

**Comment by prwhitehead** [comment]
Thank you for your reply @Envek and the tip about using shared yml variables - very useful :) 

The adapter seems to be registered correctly: 

    rb(main):001:0> ActionCable.server.config.cable 
    => {"adapter"=>"any_cable"}

I made sure all services had access to the app variables, however there doesn't seem to be a difference. The `docker-compose.yml` (in full) looks as follows: 

    version: "3.3"

    services:
      app:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        ports:
          - 3000:3000
        volumes:
          - .:/app
        depends_on:
          - db
          - webpacker
        environment: &app_env
          ACTION_CABLE_ADAPTER: any_cable
          REDIS_URL: redis://redis:6379/0
          REDIS_SIDEKIQ_URL: redis://redis:6379/1
          CABLE_URL: ws://localhost:8080/cable
          WEBPACKER_DEV_SERVER_HOST: webpacker
          ANYCABLE_REDIS_URL: redis://redis:6379/0
          ANYCABLE_RPC_HOST: anycable:50051
          ANYCABLE_HOST: 0.0.0.0
        stdin_open: true
        tty: true

      db:
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: stimulusreflex_development
          MYSQL_ROOT_PASSWORD: root
        command:
          --max_allowed_packet=1073741824
        volumes:
          - ./docker/mysql/conf.d:/etc/mysql/conf.d
          - ./docker/mysql/data:/var/lib/mysql
        ports:
          - 3306:3306
        healthcheck:
          test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
          timeout: 5s
          retries: 5

      sidekiq:
        build: .
        command: bundle exec sidekiq -C config/sidekiq.yml
        volumes:
          - .:/app
          - ./config/sidekiq.yml:/app/config/sidekiq.yml
        depends_on:
          - app
          - redis
        environment:
          <<: *app_env
          REDIS_URL: redis://redis:6379/1

      redis:
        image: redis:6.0.6
        ports:
          - 6379:6379
        volumes:
          - ./docker/redis/:/data
        command: ["--appendonly yes"]
        healthcheck:
          test: redis-cli ping
          interval: 1s
          timeout: 3s
          retries: 30

      webpacker:
        build: .
        command: bash -c "./bin/webpack-dev-server"
        volumes:
          - .:/app
        ports:
          - 3035:3035
        environment:
          <<: *app_env
          WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

      ws:
        image: anycable/anycable-go:1.0
        ports:
          - 8080:8080
        environment:
          <<: *app_env
        depends_on:
          - redis

      anycable:
        build: .
        command: bundle exec anycable
        environment:
          <<: *app_env
          ANYCABLE_DEBUG: 1
        ports:
          - 50051
        depends_on:
          - ws
          - redis

I am still seeing the following recurring error in the logs: 

        anycable_1   | RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"172.22.0.1", "cookie"=>"cookies_allowed=1; 1031b8c41dfff97a311a7ac99863bdc5_username=3c2b4e6d34d4c32848272c799b07a0082fc8cede1e35b3474d5441650b63919ea%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A7%3A%22buffalo%22%3B%7D; fontsactive_v1=1; _session_id=ef84246b21b1b5675b78394a69336f4e"}, cstate: {}, istate: {}>>
        ws_1         | E 2020-08-26T12:14:43.418Z context=ws Websocket session initialization failed: Application error: undefined method `call' for ApplicationCable::Connection:Class
        anycable_1   | undefined method `call' for ApplicationCable::Connection:Class:
        anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:18:in `connect'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
        anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
        anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `block in call'
        anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
        anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
        anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
        anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb:16:in `call'
        anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
        anycable_1   | /usr/local/bundle/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
        anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
        anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
        anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
        anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
        anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
        anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-08-26 12:14:58 +0000)

There was a note in the anycable docs about Stimulus Reflex < 3 requiring a persistent connection, however i'm using 3.2.3 so that wouldn't seem to be applicable and this is another issue, but I just wanted to mention that I had seen that and was aware. 

The whole repo is on Github as its a learning project. https://github.com/prwhitehead/StimulusReflexPlayGround

I'm a little lost as to what might be happening to prevent it from connecting.

**Comment by Envek** [comment]
I'm out of ideas for now. @palkan, any thoughts?

Btw, can't run you project:
```
webpacker_1  | yarn run v1.22.4
webpacker_1  | error Command "webpack-dev-server" not found.
webpacker_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stimulusreflexplayground_webpacker_1 exited with code 1
```

**Comment by prwhitehead** [comment]
> Btw, can't run you project:

Thanks for the heads, up, i'll have a look and fix it when I get a minute :)

The link is useful for reference, so thank you. In this case the app is working (except for webpacker right now) and action cable is functioning with both `async` and `redis` as the adapter, just not `any_cable`.

**Comment by palkan** [comment]
The exception indicates that AnyCable patches for Action Cable haven't been loaded.
Quick guess: what is your RAILS_ENV for `bundle exec anycable`?

You can check this by adding something like this to `config/initializers/anycable.rb`:

```ruby
AnyCable.configure_server do
  puts "AnyCable RPC is running in #{Rails.env}"
end
```

**Comment by prwhitehead** [comment]
Hello @palkan. Firstly, thank you for your work on this and your other projects. 

I added the code above and it seem to be running in `development`. 

    anycable_1   | AnyCable RPC is running in development
    anycable_1   | Starting AnyCable gRPC server (pid: 1, workers_num: 30)
    anycable_1   | AnyCable version: 1.0.1 (proto_version: v1)
    anycable_1   | gRPC version: 1.31.1
    anycable_1   | Serving Rails application from ./config/environment.rb
    anycable_1   | handling /anycable.RPC/Connect with #<Method: AnyCable::RPCHandler#connect>
    anycable_1   | handling /anycable.RPC/Command with #<Method: AnyCable::RPCHandler#command>
    anycable_1   | handling /anycable.RPC/Disconnect with #<Method: AnyCable::RPCHandler#disconnect>
    anycable_1   | handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check>
    anycable_1   | handling /grpc.health.v1.Health/Watch with #<Method: Grpc::Health::Checker(Grpc::Health::V1::Health::Service)#watch>
    anycable_1   | Broadcasting Redis channel: __anycable__
    anycable_1   | RPC server is starting...
    anycable_1   | RPC server is listening on anycable:50051

**Comment by palkan** [comment]
Great. Let's add more puts debugging)

Let's see what we have for:
- `ActionCable.server.config.cable `
- `AnyCable::Rails.enabled?`
- `$LOADED_FEATURES.grep(/anycable/)`

**Comment by prwhitehead** [comment]
I had to get these from the rails console, as they wouldn't output in the logs for whatever reason. Hopefully that doesn't affect their usefulness. 

    irb(main):006:0> ActionCable.server.config.cable
    => {"adapter"=>"any_cable"}

    irb(main):007:0> AnyCable::Rails.enabled?
    => true

    irb(main):008:0> $LOADED_FEATURES.grep(/anycable/)
    => ["/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/version.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/exceptions_handling.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/broadcast_adapters/base.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/broadcast_adapters.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware_chain.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/socket.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc/rpc_pb.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc/rpc_services_pb.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/health_server.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/server.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middlewares/check_version.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/version.rb", "/usr/local/bundle/gems/anycable-1.0.1/lib/anycable/config.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/config.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/rack.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/channel_state.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/railtie.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable-rails.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/log_tagging.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/middlewares/executor.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/connection/serializable_identification.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/refinements/subscriptions.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/channel.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/remote_connections.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/session_proxy.rb", "/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/connection.rb"]

**Comment by Envek** [comment]
You can launch console in anycable-rpc container with command like this:

```sh
docker-compose run anycable rails console
```

**Comment by palkan** [comment]
The output above shows that the patch is loaded (the last one—`/usr/local/bundle/gems/anycable-rails-1.0.1/lib/anycable/rails/actioncable/connection.rb`).

You can also check that it's loaded by calling `ApplicationCable::Connection.call` (should raise something different from `NoMethodError` or maybe not raise at all).

> Hopefully that doesn't affect their usefulness.

It's better to check from within AnyCable process. Simple `puts` should work (maybe, `docker-compose up` is not restarting the service, try to run `docker-compose run anycable /bin/bash` and then `bundle exec anycable` from within a container).

**Comment by prwhitehead** [comment]
I rebuilt the containers to test inside the anycable container, and it all seems to be working. 

@palkan I'm really sorry to have wasted your time, it seems that the advice give by @Envek to let all containers access the same variables really did fix the issue, but for some reason building the containers wasn't respecting the changes. 

For anyone that might find this issue in the future, the issue seems to be with the `ANYCABLE_HOST` variable. I had it set on the `ws` websocket container, when, as @Envek noted, the other app container needed access to this as well. Setting it to `ANYCABLE_HOST: 0.0.0.0` and sharing those variables seems to have fixed the connection issue. The `docker-compose.yml` posted in https://github.com/anycable/anycable-rails/issues/137#issuecomment-680844458 *is* a working copy. 

Thank you both, once again, for the time you spend making Ruby and Rails better and on Open Source, it's very much appreciated.
