### ISSUE TITLE
Anycable Rails Executable Not Handling (or Displaying) Errors

### ISSUE THREAD

**Issue by dwmcc** [anycable/anycable-rails#14]
Hi,
I'm loving working with Anycable, and it's quite simple to get set up and running.
I'm running into an issue, however, whenever there's an exception in my Rails app. More precisely, exceptions are not reported anywhere in Anycable. I have `debug` enabled in the `anycable.yml` file, and I even went so far as to modify the `Anycable::Handler::ExceptionsHandling` module to see if the errors weren't even being printed. If I simulate any sort of error, even just calling non-existent methods, there is no log output at all. If I add a non-existent method call to the middle of a method in my websocket channel and then call `.perform` for the encapsulating method, the method stops executing without any message of any sort.
Obviously, this is an issue as I want to catch errors with a reporting system so I can be notified of them on production.
Any thoughts, including how I may have misconfigured this or if I am overlooking something are appreciated.

**Comment by palkan** [comment]
Hi, @dwmcc!

Could you, please, provide a more concrete example? It would be great to have a channel code and a JS script.

> there is no log output at all

Where are you looking for logs? I mean, which process's output do you mean–RPC server (`./bin/anycable`) or WebSocket server (`anycable-go`)?

**Comment by dwmcc** [comment]
Hi @palkan - thank you for the fast response! I'm happy to provide additional information as needed.

To address your questions:
-I am looking in the RPC server `./bin/anycable` for errors, as I believe this is where they should appear.
-To test whether I could print something in the RPC server output, I first added a `puts` to `app/channels/application_cable/connection.rb` in the `connect` method (a rudimentary method of debugging but I wanted to ensure there was output):

```
# app/channels/application_cable/connection.rb
def connect
      puts "attempting to connect"
      self.current_user = find_verified_user
end
```
After testing this, the server output from `./bin/anycable` successfully puts the text on a WS connection:
```
$ ./bin/anycable
     attempting to connect
```
Next, I overrode the `Anycable::Handler::ExceptionsHandling` module and modified `connection.rb` to include a specifically invalid block of code:

```
# config/initializers/anycable_errors.rb
Anycable::Handler::ExceptionsHandling.module_eval do
  def connect(*)
    puts "should handle error!"
    super
  rescue StandardError => e
    puts "got an error"
    logger.error(e.message)
    puts e.message
    Anycable::ConnectionResponse.new(status: Anycable::Status::ERROR)
  end

... (same modifications for disconnect(*) and command(*) error handlers)

end
```

```
# app/channels/application_cable/connection.rb
def connect
      puts "attempting to connect"
      invalid_method_call()
      self.current_user = find_verified_user
end
```
As I would expect, when connecting via WS, the invalid method is called and is handled correctly:

```
./bin/anycable 
     should handle error!
     attempting to connect
     got an error
     undefined method `invalid_variable' for #<ApplicationCable::Connection:0x000000012zx525>
```
So far, this is how I would expect everything to function. The error is successfully captured and handled by the `Anycable::Handler::ExceptionsHandling` module. Now, I choose to introduce the same error into  `user_channel.rb`. Should an error occur in this channel, I would expect it would be handled just the same. I removed my false error from connection.rb and added the following to `user_channel.rb`:

```
# app/channels/user_channel.rb
def subscribed
    stream_for current_user
    puts "about to error"
    invalid_method_call()
    puts "after error"
end
```
However, upon running the RPC server:
```
./bin/anycable 
     should handle error!
     attempting to connect
     about to error
```
Once the code execution reaches the invalid call, execution of that block stops and the error is not captured.

As this is my first time working with AnyCable, am I misunderstanding the intended result, or should the error be caught? For example, I am using the `raven-ruby` gem to catch errors in my production environment. Should I any error result, I am immediately notified and I can review the error on Sentry's website. However, as I demonstrated, when running the RPC server errors are not caught and I then will not know if there are errors in my ActionCable code in the production environment.

Apologies for the long explanation. Any clarification on why this is happening is appreciated!

**Comment by palkan** [comment]
Anycable uses a `logger` instance to log everything (including errors – https://github.com/anycable/anycable/blob/master/lib/anycable/handler/exceptions_handling.rb#L10).

By default it is a no-op logger (https://github.com/anycable/anycable/blob/master/lib/anycable.rb#L22). And that doesn't look good to me(

We should set `Anycable.logger` to `Rails.logger` when using `anycable-rails`.

For now you can do that by yourself, just add this line to `./bin/anycable`:

```ruby
...
Anycable.configure do |config|
 ...
end

Anycable.logger = Rails.logger

Rails.application.eager_load!
...
```

According to capturing exceptions.

Currently, it's not possible( We need to add support for custom exception handling, smth like this:

```ruby
Anycable.exception_notifier do |ex|
  Raven.capture_exception(ex)
end
```

**Comment by dwmcc** [comment]
@palkan - thanks for this information.
I will be using `Anycable.logger = Rails.logger` as you suggested, and I absolutely agree that adding support for custom exception handling is crucial. I'm sure there are other developers that would be much more comfortable using AnyCable in production knowing that any errors will be logged and handled according to their requirements.

Thanks for your help, and for opening #22.

**Comment by dwmcc** [comment]
@palkan, one final question:

I added the `Anycable.logger = Rails.logger` in `./bin/anycable` but I do not see any noticeable difference when running the RPC server. As before, the exception is printed out (because of my customization of `Anycable::Handler::ExceptionsHandling`) when it errors in `connection.rb`, but not error is printed when an exception occurs in `user_channel.rb`.

Would you expect that I would see exceptions from both files printed in the RPC server log after adding the line to `./bin/anycable`?

**Comment by palkan** [comment]
Sorry, my bad( There was a `rescue Exception` expression in `Connection#handle_channel_command`, just fixed and released as v0.4.7.

**Comment by dwmcc** [comment]
@palkan - apologies in the delay.
I was able to pull v0.4.7 and the error now appears as intended.
However, when setting `debug: true` in the `anycable.yml` file, I observe the following after my `invalid_method_call()`:

```
D, [2017-09-16T17:15:36.365528 #14537] DEBUG -- : RPC Command: #<Anycable::CommandMessage:0x0000000507cc40>
E, [2017-09-16T17:15:36.370328 #14537] ERROR -- : undefined method `invalid_method_call' for #<UserChannel:0x00000005077ee8>
trying to capture
W, [2017-09-16T17:15:36.370684 #14537]  WARN -- : failed handler: #<GRPC::ActiveCall:0x0000000507d078>; sending status:UNKNOWN
W, [2017-09-16T17:15:36.370761 #14537]  WARN -- : undefined method `encode' for class `#<Class:NilClass>' (NameError)
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:35:in `method'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:35:in `block in marshal_proc'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:225:in `server_unary_response'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:53:in `handle_request_response'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:80:in `run_server_method'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:377:in `block in loop_handle_server_calls'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:134:in `block in loop_execute_jobs'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:131:in `loop'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:131:in `loop_execute_jobs'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:84:in `block (2 levels) in start'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:83:in `catch'
/home/user/Project/vendor/ruby/2.4.0/gems/grpc-1.6.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_server.rb:83:in `block in start'
D, [2017-09-16T17:15:36.373957 #14537] DEBUG -- : Sending status  2:NameError: undefined method `encode' for class `#<Class:NilClass>'
```
This does not happen when I don't have my custom `anycable_errors.rb` initializer, and only occurs if I enable my initializer. However, the only thing the initializer is doing is adding a
`puts "trying to capture"`:

```
# config/initializers/anycable_errors.rb
Anycable::Handler::ExceptionsHandling.module_eval do
  def connect(*)
    super
  rescue StandardError => e
    logger.error(e.message)
    Anycable::ConnectionResponse.new(status: Anycable::Status::ERROR)
    puts "trying to capture"
  end

  def disconnect(*)
    super
  rescue StandardError => e
    logger.error(e.message)
    Anycable::DisconnectResponse.new(status: Anycable::Status::ERROR)
    puts "trying to capture"
  end

  def command(*)
    super
  rescue StandardError => e
    logger.error(e.message)
    Anycable::CommandResponse.new(status: Anycable::Status::ERROR)
    puts "trying to capture"
  end
end
```

Any thoughts? Thanks so much.

**Comment by palkan** [comment]
I think the problem is with `puts "trying to capture"`, which is the return value of the method. You should return a valid message, i.e. `Anycable::ConnectionResponse`
