### ISSUE TITLE
New channels not being auto loaded, in development, until container rebuild. 

### ISSUE THREAD

**Issue by prwhitehead** [anycable/anycable-rails#140]
I'm not sure if this is the expected behaviour and for speed the channels and app business logic is cached and new files are not loaded immediately, so I want to check. 

# Tell us about your environment

**Ruby version:** 2.6.6

**Rails version:** 6.0.3.3

**`anycable` gem version:** 1.0.1

**`anycable-rails` gem version:** 1.0.2

**`grpc` gem version:** 1.17

### What did you do?

Created a new `rails g channel NewTestChannel`.

### What did you expect to happen?

After restarting the container and Rails server, expected to see the new channel being available. 

### What actually happened?

The channel was not available. 

    anycable_1   | RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"NewTestChannel\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.144.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=tpKquZrlWVtLLgyQ2xoCCeoA%2FbPYycBEC9PsWIuzWY5zuh7zNOU2tnN3x6bWFbPN9WVsqJmM0%2BOWPUrv5cpivn7N9%2BBTshGHXtuSq2LSwJ8C%2BUxtsmFJQ%2F4h2tFD6LSOV2zX8eRXWxVwBRJ6IZMPTu0juP%2B4C9Bxx2AnA%2Fopl%2BFjSmrlZoN1jVoCoMiZqUZF2QECHqca5yeXqZ%2F0VdIIp%2FSlerjW05ZcVlWpWYYEtUyNoxV7vXSl0LBe2FNlTkc9eDo7GPL0VwHTElbcuhR%2F5aOY6Ls%3D--4R3WZQaEA0sdhnu%2B--qeHLJ3C9jFTrhLvC1YZw2Q%3D%3D; _session_id=17d103da0bd95668bbe76c7930fc65f2"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
    anycable_1   | Subscription class not found: "NewTestChannel"
    anycable_1   | Channel not found: NewTestChannel:
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.2/lib/anycable/rails/refinements/subscriptions.rb:12:in `fetch'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:103:in `handle_channel_command'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:79:in `command'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.2/lib/anycable/rails/middlewares/log_tagging.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.2/lib/anycable/rails/middlewares/log_tagging.rb:16:in `call'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
    anycable_1   | /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
    anycable_1   | /usr/local/bundle/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
    anycable_1   | /usr/local/bundle/gems/anycable-rails-1.0.2/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
    anycable_1   | /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
    websocket_1  | D 2020-09-13T11:45:56.922Z context=rpc Command response: error_msg:"Channel not found: NewTestChannel"
    websocket_1  | E 2020-09-13T11:45:56.922Z context=node sid=amjWbQ4emkrGJ_vQrM03q Subscribe error: Application error: Channel not found: NewTestChannel
    websocket_1  | W 2020-09-13T11:45:56.922Z context=node sid=amjWbQ4emkrGJ_vQrM03q Failed to handle incoming message '{"command":"subscribe","identifier":"{\"channel\":\"NewTestChannel\"}"}' with error: Application error: Channel not found: NewTestChannel

After I rebuilt by containers with `docker-compose up --build` the Channel was available. 

        anycable_1   | RPC Command: <AnyCable::CommandMessage: command: "subscribe", identifier: "{\"channel\":\"NewTestChannel\"}", connection_identifiers: "{}", data: "", env: <AnyCable::Env: url: "http://localhost:8080/cable", headers: {"REMOTE_ADDR"=>"192.168.144.1", "cookie"=>"_session=5560f844aeb02d60c18bfcb9a3b1be144b72dd0142700ea9cbf227c77f76ae61; _app_session=tpKquZrlWVtLLgyQ2xoCCeoA%2FbPYycBEC9PsWIuzWY5zuh7zNOU2tnN3x6bWFbPN9WVsqJmM0%2BOWPUrv5cpivn7N9%2BBTshGHXtuSq2LSwJ8C%2BUxtsmFJQ%2F4h2tFD6LSOV2zX8eRXWxVwBRJ6IZMPTu0juP%2B4C9Bxx2AnA%2Fopl%2BFjSmrlZoN1jVoCoMiZqUZF2QECHqca5yeXqZ%2F0VdIIp%2FSlerjW05ZcVlWpWYYEtUyNoxV7vXSl0LBe2FNlTkc9eDo7GPL0VwHTElbcuhR%2F5aOY6Ls%3D--4R3WZQaEA0sdhnu%2B--qeHLJ3C9jFTrhLvC1YZw2Q%3D%3D; _session_id=d180115079226726402189c946043a82"}, cstate: {"__ltags__"=>"[]"}, istate: {}>>
        anycable_1   | NewTestChannel is transmitting the subscription confirmation
        websocket_1  | D 2020-09-13T11:51:12.602Z context=node sid=5JfN4Wa5He8kFlncNOhRM Incoming message: &{subscribe {"channel":"NewTestChannel"} }
        websocket_1  | D 2020-09-13T11:51:12.607Z context=rpc Command response: status:SUCCESS streams:"new_test_channel" transmissions:"{\"identifier\":\"{\\\"channel\\\":\\\"NewTestChannel\\\"}\",\"type\":\"confirm_subscription\"}" env:<>
        websocket_1  | D 2020-09-13T11:51:12.607Z context=node sid=5JfN4Wa5He8kFlncNOhRM Subscribed to channel: {"channel":"NewTestChannel"}
        websocket_1  | D 2020-09-13T11:51:12.607Z context=node sid=5JfN4Wa5He8kFlncNOhRM Incoming message: &{subscribe {"channel":"TestChannel"} }
        websocket_1  | D 2020-09-13T11:51:12.608Z channel={"channel":"NewTestChannel"} context=hub sid=5JfN4Wa5He8kFlncNOhRM stream=new_test_channel Subscribed
        anycable_1   | deadline is 1969-12-31 23:59:59 +0000; (now=2020-09-13 11:51:12 +0000)
        anycable_1   | schedule another job

Any light you can shed on this would be much appreciated. 

Thank you.

**Comment by Envek** [comment]
Can you please share your `Dockerfile` and `docker-compose.yml`? (maybe hidden under [details tag](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab))

I believe that autoloading should just work. The problem may be if you're adding application code into container in Dockerfile instead of mounting it into almost bare ruby image. Check [our dockerization guide](https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development) for details.

**Comment by prwhitehead** [comment]
Hello @Envek thank you for your reply. I had wondered if it was that. I've included my `Dockerfile` and `docker-compose.yml` below incase that sheds some light on an issue that might help someone else in the future, or be added to the Installation FAQs. 

### Dockerfile

	FROM prwhitehead/vips-builder:latest as vips-builder
	FROM ruby:2.6.6-buster

	# Build essentials
	RUN apt-get update \
		&& DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
			software-properties-common \
			build-essential \
			vim \
			curl \
			less \
		&& apt-get clean \
		&& rm -rf /var/cache/apt/archives/* \
		&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
		&& truncate -s 0 /var/log/*log

	# Node / Yarn
	RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
	RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
		&& echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list
	RUN apt-get update \
		&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends yarn nodejs

	# Vips for image processing
	ENV VIPSHOME /usr/local/vips
	ENV PATH $VIPSHOME/bin:$PATH
	ENV LD_LIBRARY_PATH $VIPSHOME/lib:$LD_LIBRARY_PATH
	ENV PKG_CONFIG_PATH $VIPSHOME/lib/pkgconfig:$PKG_CONFIG_PATH

	COPY --from=vips-builder /var/AptImageProcessingTools /tmp/AptImageProcessingTools
	RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $(cat /tmp/AptImageProcessingTools | xargs)

	COPY --from=vips-builder /usr/local/libvips-dev.tar.gz /usr/local/
	RUN cd /usr/local/ \
		&& tar -xvzf libvips-dev.tar.gz \
		&& rm -f libvips-dev.tar.gz \
		&& pkg-config vips --cflags

	# Clean up
	RUN apt-get clean \
		&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
		&& truncate -s 0 /var/log/*log

	WORKDIR /usr/src/app

	ENV LANG=C.UTF-8 \
	  BUNDLE_JOBS=4 \
	  BUNDLE_RETRY=3

	COPY Gemfile* package* yarn* ./
	RUN yarn install --check-files

	RUN gem update --system \
		&& gem install bundler \
		&& bundle install

	COPY . .

### docker-compose.yml

    version: "3.4"

    x-app: &app
      build: .
      tmpfs:
        - /tmp
      stdin_open: true
      tty: true
      environment: &app_env
        ACTION_CABLE_ADAPTER: any_cable
        REDIS_URL: redis://redis:6379/0
        REDIS_SIDEKIQ_URL: redis://redis:6379/1
        CABLE_URL: ws://localhost:8080/cable
        WEBPACKER_DEV_SERVER_HOST: webpacker
        ANYCABLE_REDIS_URL: redis://redis:6379/3
        ANYCABLE_RPC_HOST: anycable:50051
        ANYCABLE_HOST: 0.0.0.0
        ANYCABLE_DEBUG: 1

    services:
      rails:
        <<: *app
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        ports:
          - 3000:3000
        volumes:
          - .:/usr/src/app
        depends_on:
          - db
          - webpacker
          - websocket

      db:
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: stimulusreflex_development
          MYSQL_ROOT_PASSWORD: root
        command:
          --max_allowed_packet=1073741824
        volumes:
          - ./docker/mysql/conf.d:/etc/mysql/conf.d
          - ./docker/mysql/data:/var/lib/mysql
        ports:
          - 3306:3306
        healthcheck:
          test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
          timeout: 5s
          retries: 5

      sidekiq:
        <<: *app
        command: bundle exec sidekiq -C config/sidekiq.yml
        volumes:
          - .:/usr/src/app
          - ./config/sidekiq.yml:/usr/src/app/config/sidekiq.yml
        depends_on:
          - rails
          - redis
        environment:
          REDIS_URL: redis://redis:6379/1

      redis:
        image: redis:6.0.6
        ports:
          - 6379:6379
        volumes:
          - ./docker/redis:/data
        command: ["--appendonly yes"]
        healthcheck:
          test: redis-cli ping
          interval: 1s
          timeout: 3s
          retries: 30

      webpacker:
        <<: *app
        command: bash -c "yarn && bin/webpack-dev-server"
        volumes:
          - .:/usr/src/app
        ports:
          - 3035:3035
        environment:
          WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

      websocket:
        image: anycable/anycable-go:latest
        ports:
          - 8080:8080
        environment:
          <<: *app_env
        depends_on:
          - redis

      anycable:
        <<: *app
        command: bundle exec anycable
        ports:
          - 50051
        depends_on:
          - websocket
          - redis

**Comment by Envek** [comment]
You also need to mount application code for anycable container:
```diff
   anycable:
     <<: *app
     command: bundle exec anycable
     ports:
       - 50051
+    volumes: 
+      - .:/usr/src/app
     depends_on:
       - websocket
       - redis
```

Now it sees only the code that was added into image on `docker-compose build`, you need to mount your local working directory to that container too.

See [our dockerdev example](https://github.com/evilmartians/terraforming-rails/tree/master/examples/dockerdev) for more tips.

**Comment by prwhitehead** [comment]
Thank you @Envek sorry for the unnecessary issue. 

I've been using the following as a guide, https://github.com/anycable/anycable_rails_demo/blob/master/docker-compose.yml#L111 and missed the shared `*backend`. 

Thank you for your help, have a lovely day.
