### ISSUE TITLE
Relax the dependency on the `rails` gem

### ISSUE THREAD

**Issue by avlazarov** [anycable/anycable-rails#142]
Hey folks!

I'm trying to update a Rails app from 5 to 6, however some of the new `active*` gems have dependencies that cannot be updated due to the app's code. For example, `actionmailbox` wants us to update to `mail 2.7.1` and the latter breaks a lot of our code that relies on a previous version of that gem. Instead of adding the whole rails gem, we decided to include only what we need and skip `actionmailbox` (and a few other). The problem now is that `anycable-rails` depends on `rails`.

So my question is – can the dependency on `rails` be relaxed to just `railties` and `actioncable`?

**Comment by palkan** [comment]
> can the dependency on rails be relaxed to just railties and actioncable?

I think so. Will check.

**Comment by avlazarov** [comment]
Also `globalid`, forgot about that one.

**Comment by palkan** [comment]
Release 1.0.4.

Have a painless upgrade!)

**Comment by avlazarov** [comment]
:bow:
