### ISSUE TITLE
 json: cannot unmarshal object into Go  struct field Message.identifier of type string

### ISSUE THREAD

**Issue by wojtasss** [anycable/anycable-rails#144]
**Ruby version:** ruby 2.6.6p146

**Rails version:** Rails 6.0.3.3

**`anycable` gem version:** 6.0.3.2

**`anycable-rails` gem version:** 1.0

**`grpc` gem version:** 1.17

### What did you do?
I am manually sending subscription command to anycable

### What did you expect to happen?
I expect to subscribe channel

### What actually happened?
I have a this message in anycable console:
`WARN 2020-10-06T19:03:23.731Z context=node sid=2N1Todk-CNXU4NSau8ptU Failed to handle incoming message '{"command":"subscribe","identifier":{"channel":"MempoolChannel"}}' with error: json: cannot unmarshal object into Go
 struct field Message.identifier of type string`
I am connecting to anycable with WebsocketClient from Godot Game Engine so probably code from GDScript won't help.

PS. I have similar problem with native ActionCable but then I was able to overwrite method `append` in `ActionCable::Connection:MessageBuffer` class: 

```ruby
def append(message)

        # !!!!!!!!!!!!!!!!!! start modification
        case message 
        when Array 
          message = deep_stringify(JSON.parse(message.pack('U*')))
        end
        # !!!!!!!!!!!!!!!!!! end modification

        if valid? message
          if processing?
            receive message
          else
            buffer message
          end
        else
          connection.logger.error "Couldn't handle non-string message: #{message.class}"
        end
      end
```

deep_stringify is:
```ruby
def deep_stringify(h)
          h.transform_values{|v| v.is_a?(Hash) ? deep_stringify(v) : v}.to_json
        end
```

It would be possible to change somewhere in code incoming message like this?

**Comment by palkan** [comment]
> Failed to handle incoming message '{"command":"subscribe","identifier":{"channel":"MempoolChannel"}}'

The identifier must be a JSON string, not an object, i.e., `{"command":"subscribe","identifier":"{\"channel\":\"MempoolChannel\"}"}`.

See https://docs.anycable.io/#/v1/misc/action_cable_protocol?id=subscriptions-amp-identifiers
