### ISSUE TITLE
AnyCable-Rails For New App with Small Traffic

### ISSUE THREAD

**Issue by tleish** [anycable/anycable-rails#145]
In the article [AnyCable: Action Cable on steroids — Martian Chronicles, Evil Martians’ team blog](https://evilmartians.com/chronicles/anycable-actioncable-on-steroids) it shows the amount of ram required to run AnyCable Go vs ActionCable

![Action Cable memory usage](https://cdn.evilmartians.com/front/posts/anycable-actioncable-on-steroids/Memory3-9a66e72.png)

Is this a valid overall comparison?

If I understand the architectures correctly, 

### ActionCable Architecture
```
                                                       +------+
                          +--------------------------->+  DB  |
                          |                            +---+--+
+---------+  ws://  +-----+-----+                          ^
| Clients | +-----> |ActionCable|                          |
+----+----+         +-----+-----+                          |
     |                    ^       +---------+        +-----+-------+
     |                    +-------+  Redis  +<-------+ Application |
     |                            +---------+        +-----+-------+
     |                                                     ^
     +-----------------------------------------------------+
```
### AnyCable-Go Architecture
```
                          HTTP/2   +-----------+       +------+
                          +------->+ Rails RPC +------>+  DB  |
                          |        +-----------+       +---+--+
+---------+   ws://  +----+------+                         ^
| Clients | +------> |AnyCable Go|                         |
+----+----+          +----+------+                         |
     |                    ^       +---------+        +-----+-------+
     |                    +-------+  Redis  +<-------+ Application |
     |                            +---------+        +-----+-------+
     |                                                     ^
     +-----------------------------------------------------+
```

So, my question is... for the example in the article, what would the memory requirements be for 

- ActionCable (3.5GB)
- AnyCable Go + Rails RPC (???)

What I'm really wondering, many article on ActionCable vs AnyCable state something to the effect of "Use ActionCable if you don't have many users/connections, use AnyCable if you have lots of users/connections".  While AnyCable adds an additional server to the overall architecture, does it decrease the overall infrastructure memory/CPU requirements?  Trying to better understand tradeoffs for an initial small application.  Do I setup AnyCable now, or consider it in the future.

**Comment by Envek** [comment]
Also please read our newer blog post: [AnyCable 1.0: Four years of real-time web with Ruby and Go](https://evilmartians.com/chronicles/anycable-1-0-four-years-of-real-time-web-with-ruby-and-go)

For the resource consumption you can start at [Heroku deployment page in the docs, section “Choosing the right formation”](https://docs.anycable.io/#/v1/deployment/heroku?id=choosing-the-right-formation) (referenced in this post):

> MiB required to serve 1k connections by AnyCable-Go (currently, it equals to 50MiB for most use-cases)
> the size of the RPC (Rails) application

To run AnyCable you need to have at least one Anycable RPC server (it is your Rails application). Its memory consumption is defined by your Gemfile and your codebase. Usually it is about 400 MiB.

**So, as a ballpark estimatiuon, you will need less than 0.5GB with AnyCable for a small traffic application**

**Comment by palkan** [comment]
Thanks @Envek!

I only have one more example to add: https://twitter.com/palkan_tula/status/1224492896549769223

**Comment by tleish** [comment]
@palkan @Envek - very helpful responses, thank you.

**Comment by arpansac** [comment]
> Also please read our newer blog post: [AnyCable 1.0: Four years of real-time web with Ruby and Go](https://evilmartians.com/chronicles/anycable-1-0-four-years-of-real-time-web-with-ruby-and-go)
> 
> For the resource consumption you can start at [Heroku deployment page in the docs, section “Choosing the right formation”](https://docs.anycable.io/#/v1/deployment/heroku?id=choosing-the-right-formation) (referenced in this post):
> 
> > MiB required to serve 1k connections by AnyCable-Go (currently, it equals to 50MiB for most use-cases)
> > the size of the RPC (Rails) application
> 
> To run AnyCable you need to have at least one Anycable RPC server (it is your Rails application). Its memory consumption is defined by your Gemfile and your codebase. Usually it is about 400 MiB.
> 
> **So, as a ballpark estimatiuon, you will need less than 0.5GB with AnyCable for a small traffic application**

Thanks for this @Envek, searched the whole internet and then found it here :)

What should be the idle anycable-rails memory consumption?
I'm getting 151mb usage

And when the load goes to 50 people the RAM usage goes up to 3Gb
