### ISSUE TITLE
Unable to install with ruby 3.0

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable-rails#147]
When I attempt to install the gem with ruby 3.0, it fails when it reaches the grpc gem portion of the installation...it doesn't build the grpc. Can you please take a look at this issue?

**Comment by palkan** [comment]
Try building grpc and protobuf gems from source using these instructions: https://docs.anycable.io/#/v1/troubleshooting?id=problems-with-docker-alpine-images (`BUNDLE_FORCE_RUBY_PLATFORM=1` is important).

I can't force Google to release updates in time 🤷🏻‍♂️

**Comment by RailsCod3rFuture** [comment]
Installing protobuf worked. I will try with grpc.
