### ISSUE TITLE
Cannot get more than 1 concurrent message being received at once

### ISSUE THREAD

**Issue by d12** [anycable/anycable-rails#149]
### Tell us about your environment

**Ruby version:** 2.6.6

**Rails version:** 6.0.3.1

**`anycable` gem version:** 1.0.2

**`anycable-rails` gem version:** 1.0.4

**`grpc` gem version:** 1.35.0

### What did you do?
Hey! I've been noticing issues with backlogs forming somewhere while many messages are being received from the frontend. As a concurrency test, I added a `sleep 1` to one of my incoming message receivers in Rails. With the sleep, I can see only 1 message is being processed concurrently.

### What did you expect to happen?
I was expecting the default grpc concurrency of 30 to be used. I've also manually set concurrency using `anycable-go --port=8080 --metrics_http=/ws-metrics --debug --rpc_concurrency=30` and monitored the metrics endpoint. Nothing in the metrics seems off, and `anycable_go_rpc_pending_num` remains at 0. 

### What actually happened?
Only 1 message at a time gets processed. My application deals with a high amount of inbound messages so ideally I'm able to achieve more concurrency than this. 

Also, the same issue occurs in production (Heroku Standard 1x), and strangely bumping the number of anycable dynos doesn't make a difference, I still have only 1 message being processed per second.

Cheers!

**Edit:** I'm suspecting this may have more to do with Puma than anycable-rails, digging into it now. I'm still not sure why adding more dynos on Heroku didn't allow me to process more messages concurrently though.

**Edit 2:** Nevermind, I confirmed concurrency with Puma is working as expected with the web server, it's just the anycable message handling.

**Comment by d12** [comment]
Some logs from `anycable-go`:

```
 DEBUG 2021-01-28T17:56:23.355Z context=node sid=EyXZwglJkbgQ0Zqf1Cme7 Incoming message: &{message {"channel":"ActivityChannel","activity_instance_id":45} {"event":"draw","userId":76,"drawEvents":[[0,0,4,420,329,425,329],[0,0,4,425,329,434,329],[0,0,4,434,329,448,329],[0,0,4,448,329,463,329]]}}
 DEBUG 2021-01-28T17:56:24.364Z context=rpc Command response: status:SUCCESS env:<>
 DEBUG 2021-01-28T17:56:24.364Z context=node sid=EyXZwglJkbgQ0Zqf1Cme7 Perform result: &{false false [] [] [] [] map[] map[]}

 DEBUG 2021-01-28T17:56:24.364Z context=node sid=EyXZwglJkbgQ0Zqf1Cme7 Incoming message: &{message {"channel":"ActivityChannel","activity_instance_id":45} {"event":"draw","userId":76,"drawEvents":[[0,0,4,463,329,483,328],[0,0,4,483,328,513,322],[0,0,4,513,322,525,316]]}}
 DEBUG 2021-01-28T17:56:25.371Z context=rpc Command response: status:SUCCESS env:<>
 DEBUG 2021-01-28T17:56:25.371Z context=node sid=EyXZwglJkbgQ0Zqf1Cme7 Perform result: &{false false [] [] [] [] map[] map[]}

 DEBUG 2021-01-28T17:56:25.371Z context=node sid=EyXZwglJkbgQ0Zqf1Cme7 Incoming message: &{message {"channel":"ActivityChannel","activity_instance_id":45} {"event":"draw","userId":76,"drawEvents":[[0,0,4,525,316,543,300],[0,0,4,543,300,546,291],[0,0,4,546,291,546,281]]}}
 DEBUG 2021-01-28T17:56:26.377Z context=rpc Command response: status:SUCCESS env:<>
 DEBUG 2021-01-28T17:56:26.377Z context=node sid=EyXZwglJkbgQ0Zqf1Cme7 Perform result: &{false false [] [] [] [] map[] map[]}
 ```

**Comment by palkan** [comment]
Currently, handling incoming messages from a client is blocking: we do not consume the next message while processing the current one. If you try to send messages by different clients, you should see them handled concurrently.

While Action Cable uses a fixed size workers pool to handle incoming messages from all clients, anycable-go uses a message queue per connection.

**Comment by d12** [comment]
Ohh interesting. I just checked with multiple connections and concurrency works as expected :) Is it possible to measure these message queues so that I can tell if any clients are experiencing backlogs?

**Comment by palkan** [comment]
> Is it possible to measure these message queues

Unfortunately, no. It goes down to the underlying IO; our (Go) read buffer is only 1kb (though configurable), that the only thing we can calculate in theory.

**Comment by d12** [comment]
Gotcha, not a problem. Thanks for the swift responses!
