### ISSUE TITLE
AnyCable::CompatibilityError: @_streams?

### ISSUE THREAD

**Issue by pcreux** [anycable/anycable-rails#151]
### Tell us about your environment

**Ruby version:** ruby 2.6.6p146

**Rails version:** Rails 6.0.3.4

**`anycable` gem version:** 1.0.2

**`anycable-rails` gem version:** 1.0.4

**`grpc` gem version:** N/A

### What did you do?

I added `require "anycable/rails/compatibility"` to `config/initializers/anycable.rb`.

My channel is similar to this:

```
class ChatroomChannel < ApplicationCable::Channel
  def subscribed
    stream_from "chatroom_#{current_user.id}"
  end

  def unsubscribed
  end
end
```

### What did you expect to happen?

No error.

### What actually happened?

 But I'm seeing the following error in the logs.

```
Could not execute command from ({"command"=>"subscribe", "identifier"=>"{\"channel\":\"ChatroomChannel\"}"})
[AnyCable::CompatibilityError - Channel instance variables are not supported by AnyCable, but were set: @_streams]: gems/anycable-rails-1.0.4/lib/anycable/rails/compatibility.rb:42:in `__anycable_check_ivars__'
gems/anycable-rails-1.0.4/lib/anycable/rails/compatibility.rb:26:in `run_callbacks'
gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:180:in `subscribe_to_channel'
gems/actioncable-6.0.3.4/lib/action_cable/connection/subscriptions.rb:38:in `add'
gems/actioncable-6.0.3.4/lib/action_cable/connection/subscriptions.rb:17:in `execute_command'
```

`@_streams` is set here: https://github.com/rails/rails/blob/v6.0.3.4/actioncable/lib/action_cable/channel/streams.rb#L116-L118

**Comment by palkan** [comment]
As far as I remember, `@_streams` comes from [testing utils](https://github.com/rails/rails/blob/v6.0.3.4/actioncable/lib/action_cable/channel/test_case.rb). Does this happen in test env or in development?

**Comment by pcreux** [comment]
It happens in development.

**Comment by palkan** [comment]
Fixed and released in 1.0.5

**Comment by pcreux** [comment]
@palkan Well, I'm now getting this in dev environment:

```
AnyCable::CompatibilityError - Channel instance variables are not supported by AnyCable, but were set: @active_periodic_timers
```

**Comment by palkan** [comment]
😞
Fixed in master. Could you check please?
