### ISSUE TITLE
AnyCable Deployment Guide

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable-rails#162]
Is there anything out that helps users with easy deployment for production? I plan to use AWS for hosting.....

**Comment by Envek** [comment]
We have a whole [Deployment](https://docs.anycable.io/deployment/) section in AnyCable documentation.

However, AWS is a huge ecosystem of various services, so “plan to use AWS for hosting” doesn't really tells us much. If you plan to use AWS EKS then [Kubernetes guide](https://docs.anycable.io/deployment/kubernetes) is for you, if you plan to provision some EC2 instances by hand or using some automation then you should start with [Systemd guide](https://docs.anycable.io/deployment/systemd). There is also integration with Capistrano (old school, but still widely used).

Just get familiar with [AnyCable architecture](https://docs.anycable.io/architecture) as there are new components to deploy (compared with ActionCable).

**Comment by RailsCod3rFuture** [comment]
Thank you again for such a fast response. I am aiming to launch my rails app on AWS Elastic Beanstalk. Would the Systemd guide work better for that?

**Comment by Envek** [comment]
@RailsCod3rFuture take a look at this repository: [jetrockets/rails-elastic-beanstalk](https://github.com/jetrockets/rails-elastic-beanstalk). I haven't tried it, but it looks like the solution you want. Try it and share your experience!

**Comment by RailsCod3rFuture** [comment]
thanks
