### ISSUE TITLE
Does anycable truly depend on latest & greatest Ruby/Rails?

### ISSUE THREAD

**Issue by sdhull** [anycable/anycable-rails#164]
Hello! Thank you for this exciting project, we're looking forward to using it at my organization.

Unfortunately we're still in the process of upgrading our massive monolith to recent versions of Ruby & Rails—can you shed some light on the version requirements in the gemspec? Is Ruby >= 2.7 & Rails >= 6 really required or will this potentially work with older versions of Ruby/Rails as well?

**Comment by palkan** [comment]
> Is Ruby >= 2.7 & Rails >= 6 really required or will this potentially work with older versions of Ruby/Rails as well?

It could work but we can not guarantee this in the future; thus, we specify the versions we test against in the gemspec.

For Rails 5, you can use `anycable-rails` <1.2. You can still use newest versions of `anycable` and `anycable-go`.

**Comment by sdhull** [comment]
Thanks for the reply, that's helpful!
