### ISSUE TITLE
Anycable-rails and Seachkick together hangs the server

### ISSUE THREAD

**Issue by davidklsn** [anycable/anycable-rails#178]
I have been using Anycable in production for a year now and just love it! I added  [Searchkick](https://github.com/ankane/searchkick), but then the server just keeps freezing. Any guidance or help with this would be highly appreciated. I have a tried everything I can think of.. I have posted this issue in the Searchkick repo but they could not help me.

**What I did**
Added the Searchkick gem in a working application using Anycable. 

**What I expected**
Everything working as normal

**What happened**
Server can't take any requests and just hangs. Nothing in the logs. The client just tries to load the page until I kill the server.

I tried to isolate everything in a new rails project with the same versions. It seems to be an issue when running Anycable-rails together with Searchkick. I can reproduce the issue here: https://github.com/davidklsn/searchkick-anycable-incompatibility

OS: Ubuntu 20.04.5

**Versions**
ruby 3.0.1
rails 7.0.4

searchkick (5.1.0)
anycable (1.2.3)
anycable-rails (1.3.4)
grpc (1.50.0 x86_64-linux)

Cheers!

**Comment by palkan** [comment]
> I can reproduce the issue here: https://github.com/davidklsn/searchkick-anycable-incompatibility

What are the reproduction steps? I launched the app (`bin/rails s`) and I can the default Rails welcome page.

**Comment by davidklsn** [comment]
Okey! Thanks for trying to reproduce it. There is no more steps than that. It it is probably something  on my local machine then. I will close this issue and do further investigations. Cheers!
