### ISSUE TITLE
What's the best way to close open connections on forking?

### ISSUE THREAD

**Issue by zedtux** [anycable/anycable-rails#183]
### Tell us about your environment

**Ruby version:** 3.0.4

**Rails version:** 6.1

**`anycable` gem version:** 1.3.0

**`anycable-rails` gem version:** 1.3.7

**`grpc` gem version:** 1.54.0

### What did you do?

I am migrating my app from running ActionCable with Puma to AnyCable. I have the following code in my Puma config file:

```ruby
# frozen_string_literal: true

# Based on https://www.mongodb.com/docs/mongoid/7.5/reference/configuration/#puma
on_worker_boot do

  Mongoid::Clients.clients.each do |name, client|
    client.close
    client.reconnect
  end
end

# Based on https://www.mongodb.com/docs/mongoid/7.5/reference/configuration/#puma
before_fork do
  Mongoid.disconnect_clients
end

# ...
```

Which closes open connections to MongoDB on forking (see the MongoDB documentation link for more details).

My questions are:
* Do I have to do the same with AnyCable?
* Is there the same kind of hooks I could use to perform the same task if it's required?

Thanks for AnyCable !!

**Comment by Envek** [comment]
No, you don't need to do the same for AnyCable, as there is no forking or child process spawning in AnyCable RPC part as far as I know. Refer to [AnyCable architecture](https://docs.anycable.io/architecture) for details.

**Comment by palkan** [comment]
Yep, @Envek is correct. AnyCable RPC server uses a single process, no forking. So, no special attention is required.

**Comment by zedtux** [comment]
Thank you both for your input 👌

**Comment by Envek** [comment]
@palkan, I'm curious about [Embedded mode](https://docs.anycable.io/rails/getting_started?id=embedded-mode) though. What happens when AnyCable RPC is embedded into clustered Puma for example? Does it stay in master process? :thinking:

**Comment by palkan** [comment]
That's a good question.

> Does it stay in master process?

Yeah, I think it should, but only if we preload the app.

In a clustered Puma setup, I run an RPC server within a single worker process. Here is an example: https://github.com/anycable/anycable-twilio-hanami-demo/blob/35aa3ad6dbcb47420a0b9c86af1a0290b242675d/kaisen/config/puma.rb#L17-L26
