### ISSUE TITLE
How to stream_from channels?

### ISSUE THREAD

**Issue by firdausmaarof** [anycable/anycable-rails#21]
I have a StatusChannel and I get this `Already Subscribed to {"channel":"StatusChannel","shop_id":3}` in anycable-go logs showing its already connected.

Then, on rails log, it seems to stuck here `StatusChannel is transmitting the subscription confirmation`. If I use normal action cable, i get this message `StatusChannel is streaming from somechannel` after the previous message. I'm not sure why it doesnt stream when using anycable.

**Comment by palkan** [comment]
> If I use normal action cable, i get this message StatusChannel is streaming from somechannel

AnyCable doesn't show this message, because subscription occurs within anycable-go. There you should see (when debug mode is on, `anycable-go -log`) something like:

```
Subscribe xxx
Subscribe to stream somechannel for zzz
```

> I have a StatusChannel and I get this Already Subscribed to {"channel":"StatusChannel","shop_id":3}

That means that you're trying to subscribe to the same channel twice

**Comment by firdausmaarof** [comment]
```
Client message: &{subscribe {"channel":"StatusChannel","shop_id":3} }
Already Subscribed to {"channel":"StatusChannel","shop_id":3}
Subscribe to stream sync_status_3 for {}
```

I got this message on debug mode. What does the empty object means? Because the realtime doesnt work as when using actioncable.

**Comment by palkan** [comment]
> What does the empty object means?

This is an object with connection identifiers (none for this connection).

This is the whole output? It looks strange. Btw, which version of `anycable-go` do you use?

**Comment by firdausmaarof** [comment]
I use version 0.5.1. Btw, i managed to make it work by passing -channel="anycable". Thanks for your help.
