### ISSUE TITLE
Cookies not working

### ISSUE THREAD

**Issue by mauriballes** [anycable/anycable-rails#24]
I'm using Rails 5.1.4 and Anycable-Go 0.5.0

I have this code on my Gemfile
```ruby
...
gem 'anycable-rails'
...
```
This on my application.rb
```ruby
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Chatstesting
  class Application < Rails::Application

    config.generators do |g|
      g.test_framework :rspec,
        fixtures: true,
        view_specs: true,
        helper_specs: true,
        routing_specs: true,
        controller_specs: true,
        request_specs: true
      g.fixture_replacement :factory_girl, dir: "spec/factories"
      g.template_engine :erb
    end
    config.time_zone = 'America/La_Paz'
    config.active_record.default_timezone = :local # Or :utc

    config.action_cable.url = "ws://0.0.0.0:3334/cable"
    config.action_cable.mount_path = "ws://0.0.0.0:3334/cable"

    # config.paths.add File.join('app/controllers', 'api'), glob: File.join('**', '*.rb')
    # config.autoload_paths += Dir[Rails.root.join('app/controllers', 'api', '*')]

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end

```
This on my environment.rb
```ruby
# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!

```
My cookie var is empty when I tried to connect
```ruby
# connection.rb
def connect
  self.current_user = cookies[:username]
end

# sessions_controller.rb
def create
...
cookies[:username] = { value: @username, domain: :all }
...
end
``` 
I don't know what to do. Help me please

**Comment by palkan** [comment]
Hi, @mauriballes!

First, `config.action_cable.mount_path` should be omitted in config (or `nil`). But that's not related to the issue.

Do you use `localhost` do initiate the session? Cookies are set per domain, so you should use the same domain name for both Rails app and `anycable-go`.
See the instructions on how to share cookies between different subdomains here https://github.com/anycable/anycable/wiki/%5BEXPERIMENTAL%5D-Heroku-Deployment#my-websocket-connection-fails-with-auth-failed-error.

**Comment by mauriballes** [comment]
Yes, I use 0.0.0.0 for both. Rails app and anycable-go.

**Comment by palkan** [comment]
Ok.

So what is the exact error message/logs?

**Comment by mauriballes** [comment]
It's that I don't have cookies. Look my log:
{"QUERY_STRING"=>nil, "SCRIPT_NAME"=>"", "PATH_INFO"=>"/cable", "SERVER_PORT"=>"", "HTTP_HOST"=>nil, "rack.request.form_input"=>"", "rack.input"=>"", "rack.request.form_hash"=>{}, "HTTP_COOKIE"=>""}

The cookies are empty!

**Comment by palkan** [comment]
Ok, I see.

Do you see anything suspicious in your browser console?

Could you check the request headers in browser's dev tools? Like this (Chrome):

<img width="672" alt="screen shot 2017-11-29 at 12 06 35" src="https://user-images.githubusercontent.com/1516722/33366961-ea0cc60e-d4fd-11e7-89e7-182395dbb70b.png">

**Comment by mauriballes** [comment]
I find my problem, thanks. But my problem is that I'm working with subdomains and I can share my cookies

**Comment by palkan** [comment]
Hi @etagwerker!

AnyCable doesn't use Rails middleware stack, hence `request.session` is not populated.

Check out the proposed solution from this post: https://medium.com/@leshchuk/from-action-to-any-1e8d863dd4cf (see "Minus Rack middleware" section).
