### ISSUE TITLE
identified_by ломается из-за неочевидности очередности загрузки файлов/гемов

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-rails#25]
не знаю у кого как, но у меня ломается identified_by, используется не переопределенный в anycable_rails:

    def identified_by(*identifiers)
          super
          Array(identifiers).each do |identifier|
            define_method(identifier) do
              instance_variable_get(:"@#{identifier}") || fetch_identifier(identifier)
            end
          end
     end

а оригинальный, через attr_accessor

На коннекте нормально все, потому что они совпадают и оба используют переменные инстанса, но вот на дисконнекте облом.

Подлечил временно тем, что поставил в коннекшен классе перед определением require 

    require "anycable/rails/actioncable/connection"
   
    module ApplicationCable
      class Connection < ActionCable::Connection::Base
        identified_by :user_id

**Comment by palkan** [comment]
А как загружается `anycable-rails` (в гемфайле, где-то вручную)? И в каком окружении это происходит?

**Comment by alekseyl** [comment]
.....
# Other
gem 'nenv'

gem 'anycable-rails', '~> 0.5.0', require: false
gem 'redis'

окружение без изысков. наверху гем файла сами рельсы. 

могу целиком закинуть гемфайл, но смысл?

**Comment by palkan** [comment]
Ок

> gem 'anycable-rails', '~> 0.5.0', require: false

А где тогда происходит `require "anycable-rails"`? Это должно быть где-то в `config/application.rb` или `config/environments/<env>.rb`, до загрузки кода приложения.

**Comment by palkan** [comment]
Либо явно указать в Gemfile окружения, в которых хочется использовать anycable (по идее, только production) и убрать `require: false`:

```rb
gem 'anycable-rails', '~> 0.5.0', group: :production
```

**Comment by alekseyl** [comment]
реквайр стоит по тутору в bin/anycable

    #!/usr/bin/env ruby
    # frozen_string_literal: true
    require ::File.expand_path('../../config/environment', __FILE__)
    require "anycable-rails"

    Anycable.connection_factory = ActionCable.server.config.connection_class.call

    Rails.application.eager_load!

    ApplicationCable::Connection.clear_ws_info

    if ENV['ANYCABLE_DEPLOYMENT']
       go_thread = Thread.new do
       Process.wait Process.spawn('anycable-go')
       raise "Anycable-Go failed!"
     end

      go_thread.abort_on_exception = true
     end

     Anycable::Server.start

я бы не рекомендовал использовать в две одно, а в проде другое, это все таки сильно разные штуки, и могут быть сюрпризы. 

простой пример: экшен кабель живет вокруг рэка, а это полный набор всего миддлваре, в том числе например Warden + devise, и там где в обычном кабеле пишут: 

    current_user = env['warden'].user

в AnyCable не получится. Потом там инстансы вечно живые как дедушка Ленин, и поэтому объекты родные, а у вас сериализация и глобал айди, и т.д. Я на этот счет планирую оформить мемо.

**Comment by palkan** [comment]
> реквайр стоит по тутору в bin/anycable

Для работы броадкаста из веб-инстанса тоже нужно делать `require "anycable-rails"`, иначе он будет в _родной_ редис сообщения слать.

Но я так понимаю, проблема была не в этом.

Возможно, где-то в конфиге окружения был вызов `ApplicationCable::Connection`? Что привело к тому, что он инициировался раньше загрузки `anycable-rails`.

Проще всего попробовать поставить `binding.pry` первой строчкой в `app/channels/application_cable/connection.rb` и сразу перед `require "anycable-rails"` в `bin/anycable`, и посмотреть, что произойдет раньше (при запуске `bin/anycable`); если первое -  то смотреть, откуда оно пришло; если второе - то проблема в чем-то другом, а не порядке загрузки.

**Comment by palkan** [comment]
> Я на этот счет планирую оформить мемо, по поводу реальных различий под капотом, чтобы и самому удобно было и людям не прихдоилось копаться в коде

Это классная идея. Я подумывал об автоматизации проверки совместимости (статический анализ или динамический), но пока руки не дошли./

**Comment by alekseyl** [comment]
первая строчка из bin/anycable тянет окружение:

`require ::File.expand_path('../../config/environment', __FILE__)`

а в окружении вызов 

`Rails.application.initialize!`

приводит к тому что загружается `app/channels/application_cable/connection.rb`, и вызов происходит со старым определением identified_by

**Comment by palkan** [comment]
Разобрался. В данном случае еще и `config.eager_load = true` причастен, загружается из-за него.

По-хорошему, `anycable-rails` нужно загружать до инициализации приложения. Помимо порядка загрузки тут еще и вызов инициалайзеров из `anycable-rails` не происходит.

То есть два варианта:
- либо убираем `require: false` и перекладываем загрузку на рельсу (а точней `Bundler.require`)
- либо явно грузим в `environment.rb` перед `Rails.application.initialize!`

А из `bin/anycable` нужно вообще убрать, чтобы не смущало.

**Comment by palkan** [comment]
Поправил шаблон скрипта и сделал смачный warning, если вдруг порядок загрузки/инициализации не тот - https://github.com/anycable/anycable-rails/commit/270d31feb8a27bbcd8112ed19a622fea3c4b349c.

Зарелизил как 0.5.1

**Comment by alekseyl** [comment]
Да, мне переличило, отл!

Оба варианта работают.
