### ISSUE TITLE
Lazy loading of AR connections fix is not working

### ISSUE THREAD

**Issue by kurbaitis** [anycable/anycable-rails#27]
Hi,

this [https://github.com/anycable/anycable-rails/blob/master/lib/anycable/rails/railtie.rb#L41](https://github.com/anycable/anycable-rails/blob/master/lib/anycable/rails/railtie.rb#L41)
is sometimes loaded after the RPCHandler is initialised, therefore sometimes it does not work.

Extracting the `ActiveSupport.on_load(:active_record)` content out of the block, it works perfectly.

I think you need to think about other kind specification when to load it.

**Comment by palkan** [comment]
Hi, @kurbaitis!

> other kind specification when to load it.

That has been done in the latest version. Now AnyCable prints warning if it's loaded incorrectly (i.e. after application initialization).

**Comment by kurbaitis** [comment]
Hi @palkan,

I'm referring to the situation where I don't get the warning.

The problem it seems is when you do `Anycable::RPCHandler.prepend Anycable::Rails::ActiveRecord::ReleaseConnection
` only after AR is loaded. But the existing instance of Anycable::RPCHandler is created earlier than ActiveRecord is loaded so that prepend for current instance of rpc handler does not mean anything.

**Comment by palkan** [comment]
> But the existing instance of Anycable::RPCHandler is created earlier than ActiveRecord is loaded so that prepend for current instance of rpc handler does not mean anything.

Yep, you're right. That's the GRPC lib specifics: it doesn't use class instances, it extract methods instead.

> I'm referring to the situation where I don't get the warning.

Which version of `anycable-rails` do you use?

Also, do you `eager_load`?

I'm going to re-rewite this functionality using [interceptors](https://github.com/anycable/anycable/issues/32).

**Comment by kurbaitis** [comment]
I'm using `0.5.2`, my rails version is `5.1.2`. I don't use `eager_load`

**Comment by palkan** [comment]
> I don't use eager_load

And that is likely the cause of the problem, 'cause ActiveRecord load hook runs only after you load the first AR class.

Try to add `Rails.application.eager_load!` before running `Anycable.server.start`, that should work.

**Comment by kurbaitis** [comment]
Thanks @palkan that fixed the problem. Although I think this should be added to the Wiki or readme so that others could see the bottleneck 👍
