### ISSUE TITLE
Incompatible with action-cable-testing 

### ISSUE THREAD

**Issue by TheSmartnik** [anycable/anycable-rails#28]
Hi,

Anycable redefines default `#delegate_connection_identifiers`, where it uses connection's [`#fetch_identifier`](https://github.com/anycable/anycable-rails/blob/master/lib/anycable/rails/actioncable/channel.rb#L28), which is missing in [`ConnectionStub`](https://github.com/palkan/action-cable-testing/blob/master/lib/action_cable/channel/test_case.rb#L43-L61).

This results in an error when trying to access identifier though test.  
```
NoMethodError: undefined method `fetch_identifier'
```

The probable solution would be to use `respond_to?(:fetch_identifier)`. What do you think?

**Comment by palkan** [comment]
> What do you think?

I think, that you don't need Anycable in your test env) What's the reason to do that?

> Anycable redefines default #delegate_connection_identifiers

Frankly speaking, I don't remember why we did that; I removed it and pushed to master but...

Unfortunately, that won't help 'cause Anycable also overrides `Channel#subscribe_to_channel` which is used by `action-cable-testing`.

If you still want to use Anycable in tests, extend `ActionCable::Channel::ChannelStub`:

```ruby
module ActionCable::Channel::ChannelStub
  def subscribe_to_channel
     handle_subscribe
  end
end
```

**Comment by TheSmartnik** [comment]
> I think, that you don't need Anycable in your test env)

I totally agree and I know it's a recommended way. I was just surprised that anycable breaks and thought that maybe there is a quick way to fix it

> Unfortunately, that won't help 'cause Anycable also overrides Channel#subscribe_to_channel which is used by action-cable-testing.

Yeah, and I found one more problem override of `ActionCable::Server::Base.pubsub` and there is probably no quick way around it 🙁

Thanks for the help, though 👍

**Comment by simonoff** [comment]
@palkan hi! great work! by the way may be better to add in README info that better to use it only for production?

**Comment by palkan** [comment]
Hi @simonoff!

We do have this in the "Installation" section:

> or if you want to use built-in Action Cable server
for test and development (which is possible and recommended)

So, it's recommended to use Action Cable server in production and development.
