### ISSUE TITLE
failover support

### ISSUE THREAD

**Issue by pbrumm** [anycable/anycable-rails#3]
Are there any issues with having multiple anycable-go apps running on separate boxes for failover?  

Have you looked into adding redis-sentinel support in case redis needs to failover.

Since the grpc server will contain business logic it will need restarting.   I could see using haproxy to round robin on the grpc servers from the anycable-go box.

**Comment by palkan** [comment]
> Have you looked into adding redis-sentinel support in case redis needs to failover.

We're discussing alternative broadcasting adapters here https://github.com/anycable/anycable/issues/2.

Yes, that would be great to have Redis Sentinel as an option. Added to the list.

> Are there any issues with having multiple anycable-go apps running on separate boxes for failover?

No known issues. Although I've tried only very simple _cluster_ configurations (with different websocket servers, btw), only in development environment.

> I could see using haproxy to round robin on the grpc servers from the anycable-go box

Have you tried to use haproxy with gRPC? I guess, that would require `anycable-go` to provide a health-check endpoint?

**Comment by pbrumm** [comment]
Thanks,
I posted on that ticket.

haproxy may need some way to assess health, but thinking further I think a real queue is needed.  having 4 websocket servers and 4 ruby instances starts to feel complicated on how to handle load balancing.  especially with static grpc connections.    

do you have any documentation or scripts around how you ran your load test?   If I made some attempts at adding an nsq adapter it would be helpful to be able to run some comparisons

**Comment by palkan** [comment]
I'm using https://github.com/palkan/websocket-shootout for benchmarks. No separate AnyCable configuration for now(

**Comment by palkan** [comment]
Closing this issue in favour of general discussion in https://github.com/anycable/anycable/issues/2
