### ISSUE TITLE
devise / warden emulation or support 

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-rails#30]
I don't  think that its must be a feature for anycable-rails, since its not anycable-devise %).

May be short attention notice for all middleware unability since it's gRPC service, 
 and just an example in wiki on how to emulate warden middleware and activate devise.

**Comment by yuenlye** [comment]
Will appreciate if there is any documentation on warden emulation for anycable and rails 5.2.

**Comment by palkan** [comment]
@yuenlye Check out this [post](https://medium.com/@leshchuk/from-action-to-any-1e8d863dd4cf) by @alekseyl; there is an example snippet demonstrating how to get `current_user`  (see "Minus Rack middleware" section).

**Comment by yuenlye** [comment]
@palkan I checked that post but it looks like ActionDispatch::Cookies::EncryptedCookieJar is not available in rails 5.2. Do you know any alternative to that class?

**Comment by rus-max** [comment]
@yuenlye Maybe this [post](https://medium.com/@michaeljcoyne/securing-actioncable-connections-in-rails-using-encrypted-cookies-with-metadata-f9a22fd15532) helps for you

**Comment by yuenlye** [comment]
@palkan thank you that is exactly what I need :)

**Comment by gtarsia** [comment]
Just to clarify to others, while the normal version is:
```ruby
     def find_verified_user
       if verified_user = env['warden'].user
         verified_user
       else
         reject_unauthorized_connection
       end
     end
```
```ruby
     def find_verified_user
       env['rack.session'] = cookies.encrypted[:_my_app_session]
       if verified_user = Warden::SessionSerializer.new(env).fetch(:user)
         verified_user
       else
         reject_unauthorized_connection
       end
     end
```
Replace the `my_app` `_my_app_session` with your apps name.

**Comment by Vasfed** [comment]
App's session cookie name is in config, so more universal version would be:

```ruby
    def find_verified_user
      env['rack.session'] = cookies.encrypted[Rails.application.config.session_options[:key] || raise("No cookies key in config")]
      if (verified_user = Warden::SessionSerializer.new(env).fetch(:user))
        verified_user
      else
        reject_unauthorized_connection
      end
    end
```

**Comment by palkan** [comment]
See https://docs.anycable.io/#/using_with_rails?id=devise-authentication
