### ISSUE TITLE
Add allowed request verification

### ISSUE THREAD

**Issue by alekseyl** [anycable/anycable-rails#31]
Right now AnyCable missing allowed request verification, it's not a problem since many 
sites lived behind some reverse proxy like an nginx, and they may configure it properly to prevent asocket hijacking. 

But it's a good idea to enable such verification based on ActionCable settings, at least make a reminder for manual implementation of it since its quite simple.

**Comment by DmitryTsepelev** [comment]
Addressed in #57 :)
