### ISSUE TITLE
Sending authenticate token

### ISSUE THREAD

**Issue by ikasoumen** [anycable/anycable-rails#33]
Hi, now I'm trying to use anycable-go on heroku.
I referred [this information](https://github.com/anycable/anycable/wiki/%5BEXPERIMENTAL%5D-Heroku-Deployment) and I succeeded to deploy both of Websocket server and Rails Server.

but I want authenticate WebSocket subscription with each user's token.  like this: 

```connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    protected
      def find_verified_user
        if current_user = User.find_by(token:  request.headers[:token])
          current_user
        else
          reject_unauthorized_connection
        end
      end
  end
end
```

Can I send token to server and use it in this case?

**Comment by ikasoumen** [comment]
Oh I've found how doing this after created this issue. I can refer token through `request.params` when I am using query string. Maybe I can also use `request.headers` but I don't know how to custom headers of actioncable's handshaking. Anyway, I resolved this issue.

**Comment by palkan** [comment]
> Maybe I can also use request.headers

Yeah, it's possible to use custom headers, but you have to tell `anycable-go` to proxy them using `-headers` options (see https://github.com/anycable/anycable-go#usage)
