### ISSUE TITLE
Use puma or passenger in production

### ISSUE THREAD

**Issue by andrewostroumov** [anycable/anycable-rails#34]
Hello, I believe I can use anycable in production with 15k connections. Can I start anycable with rack? So, I might use passenger or puma.

**Comment by andrewostroumov** [comment]
How many database connection can you advice to setup?

**Comment by palkan** [comment]
If you want to start with Rack, you can just use ActionCable.

The size of DB connections pool depends on the number of _actions_ made by clients (such as subscription creation, performing channels actions) and not by the number of WS connections.

**Comment by washu** [comment]
passenger handles process spaces and scaling better
