### ISSUE TITLE
ActiveRecord connections not released if AR not loaded early

### ISSUE THREAD

**Issue by bingjyang** [anycable/anycable-rails#54]
I see this issue has been addressed [previously](https://github.com/anycable/anycable-rails/commit/3322c65385a5144dc3f278e64594eb053fe966ae#diff-0373f6dbd609318dc5c5f80fb211ba03). However, if AR is not loaded prior to `RPCHandler` being instantiated then the `ReleaseConnection` module isn't prepended in time. 

I was able to get around this by requiring `active_record/base`, but wanted to raise the issue.

**Comment by palkan** [comment]
Thanks for the report!

> However, if AR is not loaded prior to RPCHandler being instantiated then the ReleaseConnection module isn't prepended in time.

Could you, please, provide an example configuration when this could happen?

**Comment by bingjyang** [comment]
Sorry for the slow reply. 

I'm on Rails 5.2.1. It's a new project so there's not much else going on, but I'm happy to provide more info if this is not reproducible.

**Comment by palkan** [comment]
@bingjyang Check out the new version, btw; it handles AR connections in a different way

**Comment by palkan** [comment]
@bingjyang any updates?

**Comment by bingjyang** [comment]
@palkan - Sorry I haven't had a chance to upgrade yet, I'll let you know if this is solved when I do. Thanks for the awesome work.
