### ISSUE TITLE
Option to disable logging to STDOUT in development

### ISSUE THREAD

**Issue by nickjer** [anycable/anycable-rails#59]
When using `rails console` in the development environment with this gem it will force logs to output to `STDOUT` as seen here:

https://github.com/anycable/anycable-rails/blob/375d23b88a2fc9e569248ef6b6cc92450c0c9ae8/lib/anycable/rails/railtie.rb#L16-L24

Ideally, I wouldn't want this gem to alter my Rails logger. Could you add an option to disable this feature or suggest a simple way to disable it? Thanks.

**Comment by palkan** [comment]
Thanks for the report!

Fixes by 
https://github.com/anycable/anycable-rails/commit/c463968037961ac3d17f4eeba95f3fd92a657092.

Now stdout logging is only enabled within the server context (i.e. when you run `bundle exec anycable`).

**Comment by nickjer** [comment]
Thanks!
