### ISSUE TITLE
How to deploy to Heroku?

### ISSUE THREAD

**Issue by seanfcarroll** [anycable/anycable-rails#6]
How to deploy to Heroku (eg with anycable-go) ?

**Comment by palkan** [comment]
Just wrote a wiki article on Heroku Deployment, please, check it out and ask any questions –   https://github.com/anycable/anycable/wiki/%5BEXPERIMENTAL%5D-Heroku-Deployment.

**Comment by seanfcarroll** [comment]
Fantastic! Will try it out. Great write up!!
