### ISSUE TITLE
How to run daemon mode in production?

### ISSUE THREAD

**Issue by niclin** [anycable/anycable-rails#62]
I use capistrano deploy my rails application, but I don't figure out how to run anycable process on production use daemon mode and record logs?

```
# I just using stupid way 
RAILS_ENV=production bundle exec anycable --server-command "anycable-go --port 3334" &`
```

**Comment by niclin** [comment]
@palkan Thank you for your quick response 😄

**Comment by Envek** [comment]
As Capistrano not really meant to be used for process management, I'd recommend defining service as systemd unit or upstart job (depending on Linux distro you're using) and then just configure Capistrano to restart service after deploy and let the operating system to do the rest. See https://github.com/anycable/anycable-go/issues/51 for example

One more viable option is [monit](https://mmonit.com/monit/) in case if you have no root privileges on your server.
