### ISSUE TITLE
AnyCable CLI игнорирует config/anycable.yml, config/secrets.yml

### ISSUE THREAD

**Issue by chezka** [anycable/anycable-rails#63]
Доброго времени суток.

### Tell us about your environment

**Ruby version:**
ruby-2.5.3

**Rails version:**
5.2.2

**`anycable` gem version:**
0.6.0

**`anycable-rails` gem version:**
0.6.1

**`grpc` gem version:**
1.17.0

### What did you do?
Обновил anycable-rails с 0.5.5 до 0.6.1

### What did you expect to happen?
`bundle exec anycable` должен читать и использовать `config/anycable.yml`

### What actually happened?
`config/anycable.yml` игнорируется

Что происходит:
`anyway_config` загружается раньше `rails` и https://github.com/palkan/anyway_config/blob/master/lib/anyway.rb#L6 игнорируется

патч обезьяны:
В `Gemfile` добавить `gem 'anyway_config', '~> 1.4.1', require: ['anyway', 'anyway/rails/config']`

**Comment by palkan** [comment]
Спасибо за репорт! Поправим.

**Comment by palkan** [comment]
Пофиксил в  https://github.com/anycable/anycable/commit/c3d6e64ae920fc26dc0545329bc8bb5fb1bddaee; нужно обновить `anycable` (не `anycable-rails`) до 0.6.1.
