### ISSUE TITLE
Load balancer setup

### ISSUE THREAD

**Issue by kernow** [anycable/anycable-rails#64]
Hi,

We are working the following setup:

ServerA - 1 of these
* Runs anycable-go
* Runs redis

ServerB - 2 of these
* Rails a rails app
* Runs the anycable grpc gem

When websocket connections come into ServerA the anycable-go server will communication with the anycable gem over grpc and I'm planning on putting a load balancer (AWS) between the websocket and grpc servers.

Is this ok to do? Is there just 1 connection made with the grpc server or are there multiple connections? I don't really know much about grpc, I'm guessing the connections are long lived?

Thanks

**Comment by palkan** [comment]
>  Is there just 1 connection made with the grpc server or are there multiple connections?

Right now we use multiple connections (connection pool).

>  I'm guessing the connections are long lived?

Yep, connections are long-lived HTTP/2 clients.

So, you need gRPC load balancer (we've only tried with [Envoy](https://docs.anycable.io/#/go_envoy)).

I'm not sure, whether AWS support gRPC load balancing out of the box (looks like it should be possible via [Network Load Balancer](
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.htm), and they also added Envoy support for ECS: https://aws.amazon.com/blogs/compute/setting-up-an-envoy-front-proxy-on-amazon-ecs/).

**Comment by kernow** [comment]
Thanks @palkan do you know if the balancing rule needs to be sticky or if it can use round robin or other types of balancing rules?

**Comment by kernow** [comment]
Found this article while looks useful, https://blog.prefab.cloud/blog/grpc-aws-some-gotchas

**Comment by palkan** [comment]
I think, round robin should be fine. Don't see any reason for more complex strategies.
