### ISSUE TITLE
ERROR bundle exec ./bin/anycable

### ISSUE THREAD

**Issue by VasilenkoVladislav** [anycable/anycable-rails#7]
When i run bundle exec ./bin/anycable in production server,
show **bundler: not executable: ./bin/anycable**
Please, help me

**Comment by palkan** [comment]
Looks like `./bin/anycable` has wrong permissions.

Try `chmod +x ./bin/anycable`.

**Comment by VasilenkoVladislav** [comment]
Thanks!
