### ISSUE TITLE
bundler: command not found: anycable

### ISSUE THREAD

**Issue by lightninglu10** [anycable/anycable-rails#72]
### Tell us about your environment

**Ruby version:** 2.5.3

**Rails version:** 5.1.6

**`anycable` gem version:** 0.5.2

**`anycable-rails` gem version:** 0.5.5

**`grpc` gem version:** 1.6

### What did you do?
`bundle exec anycable`

### What did you expect to happen?
anycable RPC to run

### What actually happened?

```
bundler: command not found: anycable
Install missing gem executables with `bundle install`
```

**Comment by lightninglu10** [comment]
Running `bundle install --binstubs` also doesn't create an anycable executable in ./bin

**Comment by palkan** [comment]
> anycable gem version: 0.5.2

`anycable` bin has been added in version 0.6.0; so you need to upgrade the gems (see also the [upgrade notes](https://docs.anycable.io/#/upgrade_to_0_6_0)).

**Comment by lightninglu10** [comment]
Cleaned up gem installation and issue solved.
