### ISSUE TITLE
Configuring Redis for Anycable

### ISSUE THREAD

**Issue by lightninglu10** [anycable/anycable-rails#73]
Hey guys, how do we configure redis (host, ports, etc) with anycable?

**Comment by palkan** [comment]
You must provide an URL to Redis (which could include credentials) via ENV variable (`REDIS_URL` or `ANYCABLE_REDIS_URL`) or CLI option (`--redis-url`).

See [docs](https://docs.anycable.io/#/configuration)

**Comment by lightninglu10** [comment]
Is there anyway to provide that information inside of rails itself? We have a config file and previously we loaded action cable like such:


```
_default: &default_settings
  adapter:  redis
  port:     <%= Configuration.redis.port %>
  host:     <%= Configuration.redis.host %>

development:
  <<: *default_settings

test:
  <<: *default_settings
  host: localhost
  username: root
  password: ''

build: # Environment for our build system.
  <<: *default_settings

cloud:
  <<: *default_settings

production:
  <<: *default_settings
```

this makes it easier for us to do so. If that can be monkey patched in then we can take a look at that too and provide a PR for it.

**Comment by lightninglu10** [comment]
Perfect, that works well. I think this should go in the documentation somewhere!
