### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1) when trying to connect

### ISSUE THREAD

**Issue by garlou** [anycable/anycable-rails#88]
Hello

I'm having troubles starting my anycable server. It produces this error when calling createConsumer on client side.

> Rails -- Exception: ArgumentError: wrong number of arguments (given 2, expected 1)#012/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/anycable-rails-0.6.1/lib/anycable/rails/actioncable/connection.rb:34:in `initialize'#012/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/actioncable-5.1.7/lib/action_cable/server/base.rb:28:in `new'#012/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/actioncable-5.1.7/lib/action_cable/server/base.rb:28:in `call'#012/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'#012/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/mapper.rb:46:in `serve'#012/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'#012/opt/mdrevccm3_staging/shared/bundle/ruby/

printing: Rails.logger.info ActionCable.server.pubsub
> Rails -- #<ActionCable::SubscriptionAdapter::AnyCable:0x0000000005943a18>

printing: Rails.logger.info AnyCable.broadcast_adapter.channel
> Rails -- anycable-staging

My anycable.yml
```
staging:
  rpc_host: "0.0.0.0:50052"
  redis_url: "redis://localhost:6379"
  redis_channel: "anycable-staging"
  access_logs_disabled: false
  debug: true
```

My cable.yml
```
staging:
  adapter: any_cable
```

My config/environments/staging.rb
```
  config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/]
  config.action_cable.url = "wss://my_staging_url.com/cable"
```

The commands I use to start anycable:
> RAILS_ENV=staging ANYCABLE_DEBUG=1 bundle exec anycable --redis-channel=anycable-staging --rpc-host="[::]:50052"
> ANYCABLE_DEBUG=1 bin/anycable-go --rpc_host=0.0.0.0:50052 --headers=cookie,x-api-token --redis_url=redis://localhost:6379 --redis_channel=anycable-staging --host=localhost --port=3335

```
ActionCable -- Starting AnyCable gRPC server (pid: 8957)
ActionCable -- AnyCable version: 0.6.0
ActionCable -- gRPC version: 1.19.0
ActionCable -- Serving Rails application from ./config/environment.rb
ActionCable -- handling /anycable.RPC/Connect with #<Method: AnyCable::RPCHandler(AnyCable::Handler::CaptureExceptions)#connect>
ActionCable -- handling /anycable.RPC/Command with #<Method: AnyCable::RPCHandler(AnyCable::Handler::CaptureExceptions)#command>
ActionCable -- handling /anycable.RPC/Disconnect with #<Method: AnyCable::RPCHandler(AnyCable::Handler::CaptureExceptions)#disconnect>
ActionCable -- handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check>
ActionCable -- Broadcasting Redis channel: anycable-staging
ActionCable -- RPC server is starting...
ActionCable -- RPC server is listening on [::]:50052
```
```
DEBUG 2019-04-10T10:31:54.842Z context=main 🔧 🔧 🔧 Debug mode is on 🔧 🔧 🔧
  INFO 2019-04-10T10:31:54.842Z context=main Starting AnyCable v0.6.0 (pid: 9044)
 DEBUG 2019-04-10T10:31:54.843Z context=disconnector Calls rate: 10ms
  INFO 2019-04-10T10:31:54.843Z context=main Handle WebSocket connections at /cable
  INFO 2019-04-10T10:31:54.843Z context=http Starting HTTP server at localhost:3335
  INFO 2019-04-10T10:31:54.843Z context=pubsub Subscribed to Redis channel: anycable-staging

  INFO 2019-04-10T10:31:54.845Z context=rpc RPC pool initialized: 0.0.0.0:50052

```

### Tell us about your environment

**Ruby version:** 2.6.2

**Rails version:** 5.1.7

**`anycable` gem version:** 0.6.0

**`anycable-rails` gem version:** 0.6.1

**`grpc` gem version:** 1.19.0

I have multiple environments running on the same machine with exactly the same code. 
I used to have two of them (lets call them dev and dev2) running Anycable without a problem. Now I disabled dev2 and tried to enable Anycable on staging but I'm having this error.

Thanks in advance for helping us so promptly.

**Comment by palkan** [comment]
Hey @garlou!

```
config.action_cable.url = "wss://my_staging_url.com/cable"
```

Are you sure the url is correct? You should point it to `anycable-go` server, which us running on port `:3333`:

```
INFO 2019-04-10T10:31:54.843Z context=http Starting HTTP server at localhost:3335
```

The exception indicates that your client is trying to connect to a built-in Action Cable server; this line:

```
in new'#12/opt/mdrevccm3_staging/shared/bundle/ruby/2.6.0/gems/actioncable-5.1.7/lib/action_cable/server/base.rb:28:in
```

Also, do you have an explicit `mount ActionCabe.server => "/cable"` in your `routes.rb`?

**Comment by garlou** [comment]
Hi @palkan. Thanks for the quick reply.

Yes, the url is correct and I changed the port of anycable-go by specifying `--host=localhost --port=3335` when starting the anycable-go server. 

I also have this configs on my nginx proxy which works well for other environments:
```
...
upstream puma_staging_ws {
  server localhost:3335;
}
...
location /cable {
    proxy_pass http://puma_staging_ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
  }
...
```

> The exception indicates that your client is trying to connect to a built-in Action Cable server; this line:

Is there a way to confirm this? I don't have `mount ActionCabe.server => "/cable"` anywhere on the code.

Thanks once again

**Comment by garlou** [comment]
@palkan Thanks you so much for your help. The cause of the problem was the nginx `location /cable ...` being on the wrong place of the config file. It is working great now 👍
