### ISSUE TITLE
AnyCable connection factory must be configured

### ISSUE THREAD

**Issue by faisalsahil** [anycable/anycable-rails#93]
I've installed anycable-rails gem in my rails app. After installing bundle getting error 

"AnyCable connection factory must be configured. Make sure you've required a gem (e.g. `anycable-rails`) or configured `AnyCable.connection_factory` yourself"

on "bundle exec anycable" command.

Here is link https://docs.anycable.io/#/anycable_gem   that i'm following.

Thank,

**Comment by palkan** [comment]
Hey @faisalsahil!

You also need to specify the `any_cable` adapter in you `cable.yml`: https://docs.anycable.io/#/using_with_rails?id=usage

I'll update the doc to reflect this required step.

**Comment by faisalsahil** [comment]
Hi palkan,

Yes, i already specify any_cable in cable.yml file.

**Comment by palkan** [comment]
Could you please show the full output of the `bundle exec anycable` commands as long as the versions of `anycable` and `rails` gems?

**Comment by faisalsahil** [comment]
Palkan,

Here is complete response when i run above command

Starting AnyCable gRPC server (pid: 9937)
AnyCable version: 0.6.3
gRPC version: 1.20.0
Serving Rails application from ./config/environment.rb
AnyCable connection factory must be configured. Make sure you've required a gem (e.g. `anycable-rails`) or configured `AnyCable.connection_factory` yourself


.....


anycable version: 0.6.3
rails: 5.2
ruby: 2.6.2

**Comment by palkan** [comment]
Hey @faisalsahil,

Sorry for late response.

So far the only clue is that `anycable-rails` gem is not loaded.

Don't you have `gem "anycable-rails", require: false` by any change in your Gemfile?

Could you try to add `require "anycable/rails"` to you `config/application.rb` (after `Bundler.require(...)`) and try to run CLI again?

**Comment by JohanAlvarado** [comment]
I have the same issue

`Starting AnyCable gRPC server (pid: 2717)
AnyCable version: 0.6.3
gRPC version: 1.21.0
Serving Rails application from ./config/environment.rb
AnyCable connection factory must be configured. Make sure you've required a gem (e.g. `anycable-rails`) or configured `AnyCable.connection_factory` yourself`

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
Rails 5.0.7.2

**Comment by palkan** [comment]
Hey @JohanAlvarado,

Have you tried to `require "anycable/rails"` manually (see the comment above)?

**Comment by JohanAlvarado** [comment]
yes, I tried and I had the same problem @palkan

**Comment by palkan** [comment]
@JohanAlvarado could you please share the contents of you Gemfile, `config/application.rb` and `config/development.rb` (or which environment you're trying to run AnyCable in?)?

**Comment by tomjohn1028** [comment]
I was receiving this error when deploying to a _staging_ environment. After double checking the redis connection, other `AnyCable` configurations, etc I eventually found I did not have any `ActionCable` adapter configured for _staging_ in _config/cable.yml_

**Comment by sumitngupta** [comment]
We had this happen just now and found that we had to also set the `development` part of cable.yml to `adapter: any_cable`.  Everything was cool after that. The docs don't mention that and the generator doesn't set that but just in case anyone else runs across this issue and is in the same boat. 

Great libraries btw, really excited to use it.
